/**
 * RRF expression syntax — parses `{...}` and whole-line meta-command expressions into an AST.
 * Never evaluates anything (no object model, no variable values) and never throws — malformed input
 * produces `errors` entries and `{type:"error"}` nodes in their place.
 *
 * Grammar, precedence table included, read end to end from RRF `3.7.0-rc.1`
 * `src/GCodes/GCodeBuffer/ExpressionParser.cpp` (not inferred from the wiki, which doesn't document
 * this at the grammar level):
 *
 * ```
 * expr        := ternary
 * ternary     := binary(0)                                        -- ParseInternal, priority table below
 * binary(p)   := unary (binOp unary)*      -- left-assoc, except '?:' which is right-assoc
 *   binOp        priority   char(s)                                  ParseInternal ~line 184-186
 *   '?'  ':'     1          ternary (parses its 'then' at opPrio, its 'else' at opPrio-1: right-assoc)
 *   '^'          2          concat (arrays if both are arrays, else stringifies both and joins - NOT
 *                            exponentiation; see Findings on this task's own "check whether ^ also
 *                            applies to strings" trap: it does, unconditionally, for anything that
 *                            isn't a pair of arrays)
 *   '&' '&&'     3          logical AND, short-circuit
 *   '|' '||'     3          logical OR, short-circuit (SAME priority as '&' - not "AND binds tighter")
 *   '!=' '=' '==' '<' '<=' '>' '>='   4      equality/comparison ('==' and '&&'/'||' are RRF's own
 *                            accepted alternates for '=', '&', '|' - not required)
 *   '+' '-'      5
 *   '*' '/'      6
 * unary       := ('-' | '+' | '!') unary(priority 10) | '#' (identifierPath | unary(10)) | postfix
 * postfix     := primary ('[' expr ']')*     -- trailing index expressions; ParseInternal's own
 *                separate loop AFTER a primary - but see this module's "Traps" note: an identifier
 *                path (below) already consumes ITS OWN '[' indices as part of the path, so this
 *                loop's practical effect here is indexing something else (a call result, a
 *                parenthesised value, a string) - rare in real G-code, and this parser only supports
 *                it when the base is already a path node (documented simplification, not a silent
 *                gap - see Traps).
 * primary     := number | string | char
 *              | '(' expr ')'
 *              | '[' arrayLiteral ']'                    -- '[]' empty, '[e]' one element, '[e,e,]' list
 *              | '{' expr | arrayLiteral '}'              -- back-compat: '{e}' plain, '{e,...}' array
 *              | identifierPath
 * identifierPath := IDENT ( '.' IDENT | '[' expr ']' )*  ( '(' args ')' )?
 *              -- ParseIdentifierExpression, ~line 1698. A bare path with no scope prefix is an
 *              object-model reference; 'var.'/'global.'/'param.' prefixes name a variable instead
 *              (checked as string prefixes on the assembled path, not part of the grammar itself).
 *              Immediately followed by '(' -> a function call, not a path continuation.
 * args        := expr (',' expr)*
 *              -- Traps: RRF's `exists(...)` is special-cased in source to require an identifier-
 *              like argument (parsed via a recursive `ParseIdentifierExpression`, not a general
 *              expression) and to accept a leading '#'. This parser treats `exists` as an ordinary
 *              call with one general-expression argument instead - simpler, and syntax-only anyway
 *              (this package never checks whether an argument to a known function is the right
 *              *kind* of expression - see "Out of scope").
 * number      := '0x' hexDigit+ | '0b' [01]+ | digit+ ('.' digit+)? ([eE] [+-]? digit+)?
 *              -- NumericConverter::Accumulate (Duet3D/RRFLibraries), read via `gh api` since it
 *              isn't vendored in the RepRapFirmware checkout this package otherwise reads from.
 * string      := '"' ( [^"] | '""' | "'" alpha | "''" )* '"'
 *              -- ParseQuotedString, ~line 2471: '""' is one literal '"'; a single quote followed by
 *              a letter lower-cases that letter; '' is one literal '.
 * char        := "'" any-char "'"                          -- ParseCharacter, ~line 2514
 * ```
 *
 * Named constants (8) and functions (31) are the exact, complete lists from RRF's own
 * `NamedEnum(NamedConstant, ...)`/`NamedEnum(Function, ...)` macro invocations
 * (`src/GCodes/GCodeBuffer/ExpressionParser.cpp` lines 80-81) — see `./tables.ts`, generated by
 * `scripts/build-expr-tables.mjs`, not retyped by hand. An unknown function name IS a parse-time
 * error in real RRF (`ParseIdentifierExpression`: "unknown function" thrown before the call's
 * arguments are even read) — reproduced here as an error, not deferred.
 */

import { EXPRESSION_FUNCTIONS, MULTI_ARG_FUNCTIONS, NAMED_CONSTANTS, VARIADIC_FUNCTIONS } from "./tables.js";

export type ExprNode =
	| { type: "number"; value: number; raw: string; start: number; end: number }
	| { type: "string"; value: string; start: number; end: number }
	| { type: "array"; items: ReadonlyArray<ExprNode>; start: number; end: number }
	| { type: "path"; root: string; segments: ReadonlyArray<string | ExprNode>; start: number; end: number }
	| { type: "call"; name: string; args: ReadonlyArray<ExprNode>; start: number; end: number }
	| { type: "unary"; op: string; operand: ExprNode; start: number; end: number }
	| { type: "binary"; op: string; left: ExprNode; right: ExprNode; start: number; end: number }
	| { type: "ternary"; test: ExprNode; then: ExprNode; else: ExprNode; start: number; end: number }
	| { type: "constant"; name: string; start: number; end: number }
	| { type: "error"; start: number; end: number };

export interface ExprError { code: string; message: string; start: number; end: number }

export interface ParsedExpression {
	ast: ExprNode;
	errors: ReadonlyArray<ExprError>;
	/** Every object-model path referenced, root segment first, array indices normalised to `[]`
	 *  (`move.axes[0].homed` -> `"move.axes[].homed"`) so equivalent paths group together. */
	objectModelPaths: ReadonlyArray<{ path: string; start: number; end: number }>;
	variables: ReadonlyArray<{ scope: "var" | "global" | "param"; name: string; start: number; end: number }>;
	functions: ReadonlyArray<{ name: string; known: boolean; start: number; end: number }>;
}

const VARIABLE_SCOPES: ReadonlyArray<"var" | "global" | "param"> = ["var", "global", "param"];

// Priorities from ParseInternal's own table: `operators = "?^&|!=<>+-*/"`, `priorities =
// {1,2,3,3,4,4,4,4,5,5,6,6}`. `!` here stands for `!=` (a two-character operator; RRF's comment: "for
// multi-character operators <= and >= and != this is the first character").
const BINARY_PRIORITY: ReadonlyMap<string, number> = new Map([
	["?", 1], ["^", 2], ["&", 3], ["|", 3],
	["!=", 4], ["=", 4], ["<", 4], [">", 4], ["<=", 4], [">=", 4],
	["+", 5], ["-", 5], ["*", 6], ["/", 6],
]);
// The set of characters a binary operator can START with - includes '!' (only ever valid as the
// first character of '!=', never a standalone operator), which `BINARY_PRIORITY`'s own keys don't
// capture on their own (its only "!"-related key is the resolved two-character "!=").
const OPERATOR_START_CHARS: ReadonlySet<string> = new Set(["?", "^", "&", "|", "!", "=", "<", ">", "+", "-", "*", "/"]);

function isDigitCh(c: string | undefined): boolean {
	return c !== undefined && c >= "0" && c <= "9";
}
function isAlphaCh(c: string | undefined): boolean {
	return c !== undefined && ((c >= "a" && c <= "z") || (c >= "A" && c <= "Z"));
}
function isAlnumCh(c: string | undefined): boolean {
	return isAlphaCh(c) || isDigitCh(c);
}
function isHexDigitCh(c: string | undefined): boolean {
	return isDigitCh(c) || (c !== undefined && ((c >= "a" && c <= "f") || (c >= "A" && c <= "F")));
}

class Parser {
	pos = 0;
	readonly errors: Array<ExprError> = [];

	constructor(private readonly text: string, private readonly offset: number) {}

	private at(i: number): string | undefined {
		return this.text[i];
	}
	private current(): string | undefined {
		return this.text[this.pos];
	}
	private advance(): void {
		this.pos++;
	}
	private skipWs(): string | undefined {
		while (this.current() === " " || this.current() === "\t") this.advance();
		return this.current();
	}
	private abs(localPos: number): number {
		return this.offset + localPos;
	}
	private error(code: string, message: string, start: number, end: number): void {
		this.errors.push({ code, message, start: this.abs(start), end: this.abs(end) });
	}
	private errorNode(start: number, end: number): ExprNode {
		return { type: "error", start: this.abs(start), end: this.abs(end) };
	}

	/** Entry point: parse one full expression, then flag anything left over. */
	parseTop(): ExprNode {
		this.skipWs();
		const node = this.parseBinary(0);
		this.skipWs();
		if (this.pos < this.text.length) {
			this.error("trailing-content", `Unexpected '${this.current()}' after the expression`, this.pos, this.text.length);
		}
		return node;
	}

	private parseBinary(minPriority: number): ExprNode {
		let left = this.parseUnary();
		for (;;) {
			const opStart = this.pos;
			const opChar = this.skipWs();
			if (opChar === undefined) return left;
			const op = this.readBinaryOperator();
			if (op === null) return left;
			const priority = BINARY_PRIORITY.get(op)!;
			if (priority <= minPriority) {
				this.pos = opStart; // put back - this operator belongs to an outer (lower-priority) call
				return left;
			}

			if (op === "?") {
				const test = left;
				const then = this.parseBinary(priority);
				this.skipWs();
				if (this.current() !== ":") {
					this.error("expected-colon", "Expected ':' in ternary expression", this.pos, this.pos + 1);
					return { type: "ternary", test, then, else: this.errorNode(this.pos, this.pos), start: test.start, end: then.end };
				}
				this.advance();
				// Right-associative: the ':' branch parses at priority-1, matching ParseInternal's
				// `ParseInternal(..., opPrio - 1)` so a further "a ? b : c ? d : e" nests correctly.
				const elseBranch = this.parseBinary(priority - 1);
				left = { type: "ternary", test, then, else: elseBranch, start: test.start, end: elseBranch.end };
				return left; // ParseInternal's '?' case returns immediately rather than looping further
			}

			const right = this.parseBinary(priority);
			left = { type: "binary", op, left, right, start: left.start, end: right.end };
		}
	}

	/** Reads one binary operator, including the two-character forms (`==`, `&&`, `||`, `!=`, `<=`,
	 *  `>=`), normalising `==`/`&&`/`||` to their single-character canonical form (RRF's own accepted
	 *  alternates - `ParseInternal`'s "Allow == && || as alternatives to = & |"). Leaves `pos`
	 *  unadvanced (returns null) when the current character isn't an operator at all. */
	private readBinaryOperator(): string | null {
		const c = this.current();
		if (c === undefined || !OPERATOR_START_CHARS.has(c)) return null;
		this.advance();
		if (c === "!") {
			if (this.current() !== "=") {
				this.error("expected-equals", "Expected '=' after '!'", this.pos - 1, this.pos);
				return "!=";
			}
			this.advance();
			return "!=";
		}
		if ((c === "<" || c === ">") && this.current() === "=") {
			this.advance();
			return c + "=";
		}
		if ((c === "=" || c === "&" || c === "|") && this.current() === c) {
			this.advance();
		}
		return c;
	}

	private parseUnary(): ExprNode {
		const start = this.pos;
		const c = this.skipWs();
		if (c === "-" || c === "+") {
			this.advance();
			const operand = this.parseUnaryAtPriority();
			return { type: "unary", op: c, operand, start: this.abs(start), end: operand.end };
		}
		if (c === "!") {
			this.advance();
			const operand = this.parseUnaryAtPriority();
			return { type: "unary", op: "!", operand, start: this.abs(start), end: operand.end };
		}
		if (c === "#") {
			this.advance();
			// ParseInternal: "#" followed by an identifier applies the length operator to a path
			// (optimised OM-array-length lookup); otherwise it applies to a general sub-expression.
			if (isAlphaCh(this.skipWs())) {
				const operand = this.parseIdentifierOrCall();
				return { type: "unary", op: "#", operand, start: this.abs(start), end: operand.end };
			}
			const operand = this.parseUnaryAtPriority();
			return { type: "unary", op: "#", operand, start: this.abs(start), end: operand.end };
		}
		return this.parsePostfix();
	}

	/** A unary operator's own operand parses at `UNARY_PRIORITY` (`ParseInternal(val, evaluate,
	 *  UnaryPriority)`) - i.e. it binds only to another unary/primary, not to a following binary
	 *  operator (`-a + b` is `(-a) + b`, not `-(a + b)`). Since `UNARY_PRIORITY` (10) is higher than
	 *  every real binary operator's priority (max 6), this is simply "parse one unary term" - no
	 *  binary operator could ever pass the `priority <= minPriority` check in `parseBinary`. */
	private parseUnaryAtPriority(): ExprNode {
		return this.parseUnary();
	}

	private parsePostfix(): ExprNode {
		const node = this.parsePrimary();
		// See the module doc comment's "Traps": generic postfix indexing of a non-path expression
		// (`(a+b)[0]`, `"x"[0]`, `foo()[0]`) is real RRF grammar but is not supported here - only a
		// path's OWN indices (already consumed by parseIdentifierOrCall) are. A stray '[' here is
		// left for the top-level trailing-content check to flag.
		return node;
	}

	private parsePrimary(): ExprNode {
		const start = this.pos;
		const c = this.skipWs();
		if (c === undefined) {
			this.error("unexpected-end", "Expected an expression", start, start);
			return this.errorNode(start, start);
		}
		if (c === "\"") return this.parseString();
		if (c === "'") return this.parseChar();
		if (c === "(") return this.parseGroup(")", false);
		if (c === "[") return this.parseGroup("]", true);
		if (c === "{") return this.parseGroup("}", null); // null: either form, decided by a comma
		if (isDigitCh(c)) return this.parseNumber();
		if (isAlphaCh(c)) return this.parseIdentifierOrCall();
		this.error("unexpected-character", `Expected an expression, found '${c}'`, this.pos, this.pos + 1);
		this.advance();
		return this.errorNode(start, this.pos);
	}

	private parseNumber(): ExprNode {
		const start = this.pos;
		// '0x'/'0b' - NumericConverter::Accumulate (Duet3D/RRFLibraries), AcceptHex: once a hex/binary
		// prefix is seen, a fraction/exponent is no longer accepted (options &= ~AcceptFloat there).
		if (this.current() === "0" && (this.at(this.pos + 1) === "x" || this.at(this.pos + 1) === "X")) {
			this.pos += 2;
			const digitsStart = this.pos;
			while (isHexDigitCh(this.current())) this.advance();
			if (this.pos === digitsStart) this.error("bad-number", "Expected hex digits after '0x'", start, this.pos);
			const raw = this.text.slice(start, this.pos);
			return { type: "number", value: parseInt(raw, 16), raw, start: this.abs(start), end: this.abs(this.pos) };
		}
		if (this.current() === "0" && (this.at(this.pos + 1) === "b" || this.at(this.pos + 1) === "B")) {
			this.pos += 2;
			const digitsStart = this.pos;
			while (this.current() === "0" || this.current() === "1") this.advance();
			if (this.pos === digitsStart) this.error("bad-number", "Expected binary digits after '0b'", start, this.pos);
			const raw = this.text.slice(start, this.pos);
			return { type: "number", value: parseInt(this.text.slice(digitsStart, this.pos), 2), raw, start: this.abs(start), end: this.abs(this.pos) };
		}
		while (isDigitCh(this.current())) this.advance();
		if (this.current() === "." && isDigitCh(this.at(this.pos + 1))) {
			this.advance();
			while (isDigitCh(this.current())) this.advance();
		}
		if (this.current() === "e" || this.current() === "E") {
			const expStart = this.pos;
			this.advance();
			if (this.current() === "+" || this.current() === "-") this.advance();
			if (isDigitCh(this.current())) {
				while (isDigitCh(this.current())) this.advance();
			} else {
				this.pos = expStart; // "E"/"e" not followed by a number is not part of the literal
			}
		}
		const raw = this.text.slice(start, this.pos);
		return { type: "number", value: Number(raw), raw, start: this.abs(start), end: this.abs(this.pos) };
	}

	/** `ParseQuotedString`: `""` is one literal `"`; `'` followed by a letter lower-cases that
	 *  letter; `''` is one literal `'`. Same escaping convention as G-code's own quoted parameters
	 *  (`StringParser::InternalGetQuotedString`) - RRF reuses it here deliberately. */
	private parseString(): ExprNode {
		const start = this.pos;
		this.advance(); // opening quote
		let value = "";
		for (;;) {
			const c = this.current();
			if (c === undefined) {
				this.error("unterminated-string", "Unterminated string", start, this.pos);
				break;
			}
			this.advance();
			if (c < " ") {
				this.error("control-character", "Control character in string", start, this.pos);
				break;
			}
			if (c === "\"") {
				if (this.current() !== "\"") break;
				this.advance();
				value += "\"";
				continue;
			}
			if (c === "'") {
				if (isAlphaCh(this.current())) {
					value += this.current()!.toLowerCase();
					this.advance();
					continue;
				}
				if (this.current() === "'") {
					this.advance();
					value += "'";
					continue;
				}
			}
			value += c;
		}
		return { type: "string", value, start: this.abs(start), end: this.abs(this.pos) };
	}

	/** `ParseCharacter`: exactly `'` + one character + `'`. Represented as a one-character string. */
	private parseChar(): ExprNode {
		const start = this.pos;
		this.advance();
		const c = this.current();
		if (c === undefined) {
			this.error("unterminated-char", "Unterminated character literal", start, this.pos);
			return this.errorNode(start, this.pos);
		}
		this.advance();
		if (this.current() !== "'") {
			this.error("expected-quote", "Expected \"'\" to close the character literal", start, this.pos);
			return { type: "string", value: c, start: this.abs(start), end: this.abs(this.pos) };
		}
		this.advance();
		return { type: "string", value: c, start: this.abs(start), end: this.abs(this.pos) };
	}

	/** `(...)`, `[...]` and `{...}` — `ParseExpectKet`/`ParseGeneralArray`. `arrayShape` is `true` for
	 *  `[`, `false` for `(` (never an array), `null` for `{` (either, decided by a trailing comma). */
	private parseGroup(closer: string, arrayShape: boolean | null): ExprNode {
		const start = this.pos;
		this.advance(); // opening bracket
		this.skipWs();
		if (arrayShape === true && this.current() === closer) {
			this.advance();
			return { type: "array", items: [], start: this.abs(start), end: this.abs(this.pos) };
		}
		const first = this.parseBinary(0);
		this.skipWs();
		if (this.current() === closer) {
			this.advance();
			if (arrayShape === true) {
				return { type: "array", items: [first], start: this.abs(start), end: this.abs(this.pos) };
			}
			return first;
		}
		if (this.current() === "," && arrayShape !== false) {
			const items = [first];
			while (this.current() === ",") {
				this.advance();
				this.skipWs();
				if (this.current() === closer) break; // trailing comma
				items.push(this.parseBinary(0));
				this.skipWs();
			}
			if (this.current() !== closer) {
				this.error("expected-closing-bracket", `Expected '${closer}'`, this.pos, this.pos + 1);
			} else {
				this.advance();
			}
			return { type: "array", items, start: this.abs(start), end: this.abs(this.pos) };
		}
		this.error("expected-closing-bracket", `Expected '${closer}'`, this.pos, this.pos + 1);
		return { type: "error", start: this.abs(start), end: this.abs(this.pos) };
	}

	/** Identifiers, dotted/indexed object-model paths, and function calls —
	 *  `ParseIdentifierExpression`. A name immediately followed by `(` is a call; a recognised named
	 *  constant (`true`/`false`/`null`/`pi`/`iterations`/`result`/`line`/`input`) short-circuits to a
	 *  `constant` node before either check, matching source's own order (constants are checked
	 *  first, then function calls, then plain paths). */
	private parseIdentifierOrCall(): ExprNode {
		const start = this.pos;
		const segments: Array<string> = [];
		let current = "";
		for (;;) {
			const c = this.current();
			if (isAlnumCh(c) || c === "_") {
				current += c;
				this.advance();
				continue;
			}
			if (c === ".") {
				segments.push(current);
				current = "";
				this.advance();
				continue;
			}
			break;
		}
		segments.push(current);
		const name = segments.join(".");
		const nameEnd = this.pos;

		if (segments.length === 1 && NAMED_CONSTANTS.has(name)) {
			return { type: "constant", name, start: this.abs(start), end: this.abs(nameEnd) };
		}

		// Object-model index segments interleaved with dotted names, e.g. "move.axes[0].homed".
		const pathSegments: Array<string | ExprNode> = [];
		for (const seg of segments) pathSegments.push(seg);
		while (this.current() === "[") {
			this.advance();
			const index = this.parseBinary(0);
			this.skipWs();
			if (this.current() !== "]") {
				this.error("expected-bracket", "Expected ']'", this.pos, this.pos + 1);
			} else {
				this.advance();
			}
			pathSegments.push(index);
			// A dotted continuation after an index, e.g. "move.axes[0].homed".
			if (this.current() === ".") {
				this.advance();
				let next = "";
				while (isAlnumCh(this.current()) || this.current() === "_") {
					next += this.current();
					this.advance();
				}
				pathSegments.push(next);
			}
		}
		const pathEnd = this.pos;

		if (this.skipWs() === "(") {
			this.advance();
			return this.parseCall(name, start);
		}

		return { type: "path", root: segments[0], segments: pathSegments, start: this.abs(start), end: this.abs(pathEnd) };
	}

	private parseCall(name: string, start: number): ExprNode {
		const known = EXPRESSION_FUNCTIONS.has(name);
		if (!known) {
			// RRF: ParseIdentifierExpression throws "unknown function" here, before even reading the
			// arguments - a real parse-time error, not deferred to evaluation.
			this.error("unknown-function", `Unknown function '${name}'`, start, this.pos);
		}
		const args: Array<ExprNode> = [];
		this.skipWs();
		if (this.current() !== ")") {
			args.push(this.parseBinary(0));
			this.skipWs();
			const wantsMore = MULTI_ARG_FUNCTIONS.has(name) || VARIADIC_FUNCTIONS.has(name);
			while (this.current() === "," && (wantsMore || !known)) {
				this.advance();
				args.push(this.parseBinary(0));
				this.skipWs();
			}
		}
		if (this.current() !== ")") {
			this.error("expected-paren", "Expected ')'", this.pos, this.pos + 1);
		} else {
			this.advance();
		}
		return { type: "call", name, args, start: this.abs(start), end: this.abs(this.pos) };
	}
}

/** Joins path segments with '.', collapsing "name.[]" to "name[]" (an index directly follows the
 *  name it indexes, not a further dotted member) so `move.axes[0].homed` normalises to
 *  `move.axes[].homed`, not `move.axes.[].homed`. */
function joinSegments(segments: ReadonlyArray<string | ExprNode>): string {
	return segments.map((s) => (typeof s === "string" ? s : "[]")).join(".").replace(/\.\[\]/g, "[]");
}

function walk(
	node: ExprNode,
	objectModelPaths: Array<{ path: string; start: number; end: number }>,
	variables: Array<{ scope: "var" | "global" | "param"; name: string; start: number; end: number }>,
	functions: Array<{ name: string; known: boolean; start: number; end: number }>,
): void {
	switch (node.type) {
		case "path": {
			const scope = VARIABLE_SCOPES.find((s) => node.root === s);
			if (scope !== undefined && typeof node.segments[1] === "string") {
				variables.push({ scope, name: joinSegments(node.segments.slice(1)), start: node.start, end: node.end });
			} else {
				objectModelPaths.push({ path: joinSegments(node.segments), start: node.start, end: node.end });
			}
			for (const seg of node.segments) if (typeof seg !== "string") walk(seg, objectModelPaths, variables, functions);
			break;
		}
		case "call":
			functions.push({ name: node.name, known: EXPRESSION_FUNCTIONS.has(node.name), start: node.start, end: node.end });
			for (const a of node.args) walk(a, objectModelPaths, variables, functions);
			break;
		case "array":
			for (const i of node.items) walk(i, objectModelPaths, variables, functions);
			break;
		case "unary":
			walk(node.operand, objectModelPaths, variables, functions);
			break;
		case "binary":
			walk(node.left, objectModelPaths, variables, functions);
			walk(node.right, objectModelPaths, variables, functions);
			break;
		case "ternary":
			walk(node.test, objectModelPaths, variables, functions);
			walk(node.then, objectModelPaths, variables, functions);
			walk(node.else, objectModelPaths, variables, functions);
			break;
		default:
			break; // number, string, constant, error - nothing to collect
	}
}

/** Parse one RRF expression. `offset` shifts every span so callers embedding this in a larger text
 *  (a `{...}` parameter's contents, say) get absolute positions directly. Never throws. */
export function parseExpression(text: string, offset = 0): ParsedExpression {
	const parser = new Parser(text, offset);
	const ast = parser.parseTop();
	const objectModelPaths: Array<{ path: string; start: number; end: number }> = [];
	const variables: Array<{ scope: "var" | "global" | "param"; name: string; start: number; end: number }> = [];
	const functions: Array<{ name: string; known: boolean; start: number; end: number }> = [];
	walk(ast, objectModelPaths, variables, functions);
	return { ast, errors: parser.errors, objectModelPaths, variables, functions };
}
