/**
 * RRF's expression functions and named constants — generated by `scripts/build-expr-tables.mjs`
 * from src/GCodes/GCodeBuffer/ExpressionParser.cpp at RRF 3.7.0-rc.1, `NamedEnum(NamedConstant, ...)` (line 80) and
 * `NamedEnum(Function, ...)` (line 81). Do not hand-edit; re-run the script instead.
 *
 * Cross-checked 2026-09-14 against `@duet3d/monacotokens@3.7.0-rc.1`'s
 * `dist/expressions/expressions.json`: identical function and constant name lists, no discrepancy
 * (see docs/wiki-discrepancies.md).
 */

export const EXPRESSION_FUNCTIONS: ReadonlySet<string> = new Set([
	"abs",
	"acos",
	"asin",
	"atan",
	"atan2",
	"ceil",
	"cos",
	"datetime",
	"degrees",
	"drop",
	"exists",
	"exp",
	"fileexists",
	"fileread",
	"find",
	"floor",
	"isnan",
	"log",
	"max",
	"min",
	"mod",
	"pow",
	"radians",
	"random",
	"round",
	"sin",
	"sqrt",
	"square",
	"take",
	"tan",
	"vector",
]);

export const NAMED_CONSTANTS: ReadonlySet<string> = new Set([
	"false",
	"iterations",
	"line",
	"null",
	"pi",
	"result",
	"true",
	"input",
]);

/** Functions that take one required argument BEYOND the first (parenthesised) one, read via a
 *  comma - e.g. `mod(a, b)`, `fileread(path, skip, count, sep)` (three more). Not a full arity
 *  table (this package doesn't validate call arity - see task 07's "out of scope"); recorded only so
 *  the parser knows to expect a comma after these without erroring on a single-argument call to one
 *  of them, and to keep looping for `fileread`'s extra operands. */
export const MULTI_ARG_FUNCTIONS: ReadonlySet<string> = new Set(["atan2", "mod", "pow", "take", "drop", "find", "fileread", "vector"]);

/** `max`/`min`: one array argument, OR two-or-more comma-separated scalar arguments. */
export const VARIADIC_FUNCTIONS: ReadonlySet<string> = new Set(["max", "min"]);
