/**
 * Object-model path existence/deprecation per RRF release (task 11, docs/tasks/11-object-model-schema.md).
 * GENERATED by scripts/build-om-schema.mjs - do not hand-edit; edit the generator and re-run it.
 * "since" omitted = present at the oldest tracked version ("3.6.3"); "until" omitted
 * = still present at the newest ("3.7.0-rc.1").
 */

import { OBJECT_MODEL_VERSIONS } from "./versions.js";

export interface ObjectModelPathEntry {
	path: string;
	since?: string;
	until?: string;
	deprecated?: { since: string; message: string };
}

/** Every known path with its lifetime, exported so other generators (task 12's release-events store)
 *  can turn "path added/removed/deprecated at version X" straight into a ChangeEvent without
 *  re-deriving this data. */
export const OBJECT_MODEL_PATHS: ReadonlyArray<ObjectModelPathEntry> = [
	{
		"path": "boards"
	},
	{
		"path": "boards[].accelerometer"
	},
	{
		"path": "boards[].accelerometer.orientation"
	},
	{
		"path": "boards[].accelerometer.points"
	},
	{
		"path": "boards[].accelerometer.resolution",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "boards[].accelerometer.runs"
	},
	{
		"path": "boards[].accelerometer.samplingRate",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "boards[].bootloaderFileName",
		"until": "3.6.3"
	},
	{
		"path": "boards[].canAddress"
	},
	{
		"path": "boards[].closedLoop"
	},
	{
		"path": "boards[].closedLoop.points"
	},
	{
		"path": "boards[].closedLoop.runs"
	},
	{
		"path": "boards[].directDisplay"
	},
	{
		"path": "boards[].directDisplay.encoder"
	},
	{
		"path": "boards[].directDisplay.encoder.pulsesPerClick"
	},
	{
		"path": "boards[].directDisplay.screen"
	},
	{
		"path": "boards[].directDisplay.screen.colourBits",
		"until": "3.6.3"
	},
	{
		"path": "boards[].directDisplay.screen.contrast"
	},
	{
		"path": "boards[].directDisplay.screen.controller"
	},
	{
		"path": "boards[].directDisplay.screen.height",
		"until": "3.6.3"
	},
	{
		"path": "boards[].directDisplay.screen.resistorRatio"
	},
	{
		"path": "boards[].directDisplay.screen.spiFreq",
		"until": "3.6.3"
	},
	{
		"path": "boards[].directDisplay.screen.width",
		"until": "3.6.3"
	},
	{
		"path": "boards[].drivers"
	},
	{
		"path": "boards[].drivers[].closedLoop",
		"until": "3.6.3"
	},
	{
		"path": "boards[].drivers[].closedLoop.currentFraction"
	},
	{
		"path": "boards[].drivers[].closedLoop.positionError"
	},
	{
		"path": "boards[].drivers[].config.direction",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "boards[].drivers[].config.mode",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "boards[].drivers[].status",
		"until": "3.6.3"
	},
	{
		"path": "boards[].firmwareDate"
	},
	{
		"path": "boards[].firmwareFileName"
	},
	{
		"path": "boards[].firmwareName"
	},
	{
		"path": "boards[].firmwareVersion"
	},
	{
		"path": "boards[].freeRam"
	},
	{
		"path": "boards[].iapFileNameSBC"
	},
	{
		"path": "boards[].iapFileNameSD"
	},
	{
		"path": "boards[].inductiveSensor"
	},
	{
		"path": "boards[].maxHeaters"
	},
	{
		"path": "boards[].maxMotors"
	},
	{
		"path": "boards[].mcuTemp"
	},
	{
		"path": "boards[].mcuTemp.current"
	},
	{
		"path": "boards[].mcuTemp.max"
	},
	{
		"path": "boards[].mcuTemp.min"
	},
	{
		"path": "boards[].name"
	},
	{
		"path": "boards[].shortName"
	},
	{
		"path": "boards[].state"
	},
	{
		"path": "boards[].supportsDirectDisplay"
	},
	{
		"path": "boards[].timeout",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "boards[].uniqueId"
	},
	{
		"path": "boards[].v12"
	},
	{
		"path": "boards[].v12.current"
	},
	{
		"path": "boards[].v12.max"
	},
	{
		"path": "boards[].v12.min"
	},
	{
		"path": "boards[].vIn"
	},
	{
		"path": "boards[].vIn.current"
	},
	{
		"path": "boards[].vIn.max"
	},
	{
		"path": "boards[].vIn.min"
	},
	{
		"path": "boards[].wifiFirmwareFileName"
	},
	{
		"path": "directories"
	},
	{
		"path": "directories.filaments"
	},
	{
		"path": "directories.firmware"
	},
	{
		"path": "directories.gCodes"
	},
	{
		"path": "directories.macros"
	},
	{
		"path": "directories.menu"
	},
	{
		"path": "directories.system"
	},
	{
		"path": "directories.web"
	},
	{
		"path": "fans"
	},
	{
		"path": "fans[].actualValue"
	},
	{
		"path": "fans[].blip"
	},
	{
		"path": "fans[].frequency"
	},
	{
		"path": "fans[].max"
	},
	{
		"path": "fans[].min"
	},
	{
		"path": "fans[].name"
	},
	{
		"path": "fans[].requestedValue"
	},
	{
		"path": "fans[].rpm"
	},
	{
		"path": "fans[].tachoPpr"
	},
	{
		"path": "fans[].thermostatic"
	},
	{
		"path": "fans[].thermostatic.heaters",
		"until": "3.6.3"
	},
	{
		"path": "fans[].thermostatic.highTemperature"
	},
	{
		"path": "fans[].thermostatic.lowTemperature"
	},
	{
		"path": "fans[].thermostatic.sensors"
	},
	{
		"path": "global"
	},
	{
		"path": "heat"
	},
	{
		"path": "heat.bedHeaterMapping",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "heat.bedHeaters",
		"deprecated": {
			"since": "3.6.3",
			"message": "use bedHeaterMapping instead"
		}
	},
	{
		"path": "heat.chamberHeaterMapping",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "heat.chamberHeaters",
		"deprecated": {
			"since": "3.6.3",
			"message": "use chamberHeaterMapping instead"
		}
	},
	{
		"path": "heat.coldExtrudeTemperature"
	},
	{
		"path": "heat.coldRetractTemperature"
	},
	{
		"path": "heat.heaters"
	},
	{
		"path": "heat.heaters[].active"
	},
	{
		"path": "heat.heaters[].avgPwm"
	},
	{
		"path": "heat.heaters[].current"
	},
	{
		"path": "heat.heaters[].extrPwmBoost"
	},
	{
		"path": "heat.heaters[].extrTempBoost"
	},
	{
		"path": "heat.heaters[].max"
	},
	{
		"path": "heat.heaters[].maxBadReadings"
	},
	{
		"path": "heat.heaters[].maxHeatingFaultTime"
	},
	{
		"path": "heat.heaters[].maxTempExcursion"
	},
	{
		"path": "heat.heaters[].min"
	},
	{
		"path": "heat.heaters[].model"
	},
	{
		"path": "heat.heaters[].model.coolingExp"
	},
	{
		"path": "heat.heaters[].model.coolingRate"
	},
	{
		"path": "heat.heaters[].model.deadTime"
	},
	{
		"path": "heat.heaters[].model.enabled"
	},
	{
		"path": "heat.heaters[].model.fanCoolingRate"
	},
	{
		"path": "heat.heaters[].model.heatingRate"
	},
	{
		"path": "heat.heaters[].model.inverted"
	},
	{
		"path": "heat.heaters[].model.maxPwm"
	},
	{
		"path": "heat.heaters[].model.pid"
	},
	{
		"path": "heat.heaters[].model.pid.d"
	},
	{
		"path": "heat.heaters[].model.pid.i"
	},
	{
		"path": "heat.heaters[].model.pid.overridden",
		"until": "3.6.3"
	},
	{
		"path": "heat.heaters[].model.pid.p"
	},
	{
		"path": "heat.heaters[].model.pid.used"
	},
	{
		"path": "heat.heaters[].model.standardVoltage"
	},
	{
		"path": "heat.heaters[].monitors"
	},
	{
		"path": "heat.heaters[].monitors[].action"
	},
	{
		"path": "heat.heaters[].monitors[].condition"
	},
	{
		"path": "heat.heaters[].monitors[].limit"
	},
	{
		"path": "heat.heaters[].monitors[].sensor"
	},
	{
		"path": "heat.heaters[].sensor"
	},
	{
		"path": "heat.heaters[].standby"
	},
	{
		"path": "heat.heaters[].state"
	},
	{
		"path": "inputs"
	},
	{
		"path": "inputs[].active"
	},
	{
		"path": "inputs[].axesRelative"
	},
	{
		"path": "inputs[].compatibility"
	},
	{
		"path": "inputs[].currentFile",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "inputs[].distanceUnit"
	},
	{
		"path": "inputs[].drivesRelative"
	},
	{
		"path": "inputs[].feedRate"
	},
	{
		"path": "inputs[].inMacro"
	},
	{
		"path": "inputs[].inverseTimeMode",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "inputs[].lineNumber"
	},
	{
		"path": "inputs[].macroRestartable"
	},
	{
		"path": "inputs[].motionSystem"
	},
	{
		"path": "inputs[].name"
	},
	{
		"path": "inputs[].selectedPlane"
	},
	{
		"path": "inputs[].stackDepth"
	},
	{
		"path": "inputs[].state"
	},
	{
		"path": "inputs[].volumetric"
	},
	{
		"path": "job"
	},
	{
		"path": "job.build"
	},
	{
		"path": "job.build.currentObject"
	},
	{
		"path": "job.build.m486Names",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.build.m486Numbers",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.build.m486names",
		"until": "3.6.3"
	},
	{
		"path": "job.build.m486numbers",
		"until": "3.6.3"
	},
	{
		"path": "job.build.objects"
	},
	{
		"path": "job.build.objects[].cancelled"
	},
	{
		"path": "job.build.objects[].name"
	},
	{
		"path": "job.build.objects[].x"
	},
	{
		"path": "job.build.objects[].y"
	},
	{
		"path": "job.duration"
	},
	{
		"path": "job.file"
	},
	{
		"path": "job.file.customInfo"
	},
	{
		"path": "job.file.filament"
	},
	{
		"path": "job.file.fileName"
	},
	{
		"path": "job.file.generatedBy"
	},
	{
		"path": "job.file.height"
	},
	{
		"path": "job.file.lastModified"
	},
	{
		"path": "job.file.layerHeight"
	},
	{
		"path": "job.file.numLayers"
	},
	{
		"path": "job.file.printTime"
	},
	{
		"path": "job.file.simulatedTime"
	},
	{
		"path": "job.file.size"
	},
	{
		"path": "job.file.thumbnails"
	},
	{
		"path": "job.file.thumbnails[].data"
	},
	{
		"path": "job.file.thumbnails[].format"
	},
	{
		"path": "job.file.thumbnails[].height"
	},
	{
		"path": "job.file.thumbnails[].offset"
	},
	{
		"path": "job.file.thumbnails[].size"
	},
	{
		"path": "job.file.thumbnails[].width"
	},
	{
		"path": "job.filePosition"
	},
	{
		"path": "job.lastDuration"
	},
	{
		"path": "job.lastFileAborted"
	},
	{
		"path": "job.lastFileCancelled"
	},
	{
		"path": "job.lastFileName"
	},
	{
		"path": "job.lastFileSimulated"
	},
	{
		"path": "job.lastWarmUpDuration"
	},
	{
		"path": "job.layer"
	},
	{
		"path": "job.layerTime"
	},
	{
		"path": "job.layers"
	},
	{
		"path": "job.layers[].duration"
	},
	{
		"path": "job.layers[].filament",
		"deprecated": {
			"since": "3.6.3",
			"message": "use filamentUsage instead"
		}
	},
	{
		"path": "job.layers[].filamentUsage",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.layers[].fractionPrinted"
	},
	{
		"path": "job.layers[].height"
	},
	{
		"path": "job.layers[].temperatures"
	},
	{
		"path": "job.pauseDuration"
	},
	{
		"path": "job.rawExtrusion"
	},
	{
		"path": "job.timesLeft"
	},
	{
		"path": "job.timesLeft.filament"
	},
	{
		"path": "job.timesLeft.file"
	},
	{
		"path": "job.timesLeft.slicer"
	},
	{
		"path": "job.timesLeft.toPause"
	},
	{
		"path": "job.warmUpDuration"
	},
	{
		"path": "ledStrips"
	},
	{
		"path": "ledStrips[].board"
	},
	{
		"path": "ledStrips[].colorOrder",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "ledStrips[].maxLeds",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "ledStrips[].pin"
	},
	{
		"path": "ledStrips[].stopMovement"
	},
	{
		"path": "ledStrips[].type"
	},
	{
		"path": "limits"
	},
	{
		"path": "limits.axes"
	},
	{
		"path": "limits.axesPlusExtruders"
	},
	{
		"path": "limits.bedHeaters"
	},
	{
		"path": "limits.boards"
	},
	{
		"path": "limits.chamberHeaters"
	},
	{
		"path": "limits.drivers"
	},
	{
		"path": "limits.driversPerAxis"
	},
	{
		"path": "limits.extruders"
	},
	{
		"path": "limits.extrudersPerTool"
	},
	{
		"path": "limits.fans"
	},
	{
		"path": "limits.gpInPorts"
	},
	{
		"path": "limits.gpOutPorts"
	},
	{
		"path": "limits.heaters"
	},
	{
		"path": "limits.heatersPerTool"
	},
	{
		"path": "limits.ledStrips"
	},
	{
		"path": "limits.monitorsPerHeater"
	},
	{
		"path": "limits.portsPerHeater"
	},
	{
		"path": "limits.reportedAxes"
	},
	{
		"path": "limits.restorePoints"
	},
	{
		"path": "limits.sensors"
	},
	{
		"path": "limits.spindles"
	},
	{
		"path": "limits.tools"
	},
	{
		"path": "limits.trackedObjects"
	},
	{
		"path": "limits.triggers"
	},
	{
		"path": "limits.volumes"
	},
	{
		"path": "limits.workplaces"
	},
	{
		"path": "limits.zProbeProgramBytes"
	},
	{
		"path": "limits.zProbes"
	},
	{
		"path": "move"
	},
	{
		"path": "move.accelerationTime"
	},
	{
		"path": "move.axes"
	},
	{
		"path": "move.axes[].acceleration"
	},
	{
		"path": "move.axes[].babystep"
	},
	{
		"path": "move.axes[].backlash"
	},
	{
		"path": "move.axes[].current"
	},
	{
		"path": "move.axes[].drivers"
	},
	{
		"path": "move.axes[].homed"
	},
	{
		"path": "move.axes[].jerk"
	},
	{
		"path": "move.axes[].letter"
	},
	{
		"path": "move.axes[].machinePosition"
	},
	{
		"path": "move.axes[].max"
	},
	{
		"path": "move.axes[].maxProbed"
	},
	{
		"path": "move.axes[].microstepping"
	},
	{
		"path": "move.axes[].microstepping.interpolated"
	},
	{
		"path": "move.axes[].microstepping.value"
	},
	{
		"path": "move.axes[].min"
	},
	{
		"path": "move.axes[].minProbed"
	},
	{
		"path": "move.axes[].percentCurrent"
	},
	{
		"path": "move.axes[].percentStstCurrent"
	},
	{
		"path": "move.axes[].phaseStep"
	},
	{
		"path": "move.axes[].printingJerk"
	},
	{
		"path": "move.axes[].reducedAcceleration"
	},
	{
		"path": "move.axes[].speed"
	},
	{
		"path": "move.axes[].stepPos"
	},
	{
		"path": "move.axes[].stepsPerMm"
	},
	{
		"path": "move.axes[].userPosition"
	},
	{
		"path": "move.axes[].visible"
	},
	{
		"path": "move.axes[].workplaceOffsets"
	},
	{
		"path": "move.backlashFactor"
	},
	{
		"path": "move.calibration"
	},
	{
		"path": "move.calibration.final"
	},
	{
		"path": "move.calibration.final.deviation"
	},
	{
		"path": "move.calibration.final.mean"
	},
	{
		"path": "move.calibration.initial"
	},
	{
		"path": "move.calibration.initial.deviation"
	},
	{
		"path": "move.calibration.initial.mean"
	},
	{
		"path": "move.calibration.numFactors"
	},
	{
		"path": "move.compensation"
	},
	{
		"path": "move.compensation.fadeHeight"
	},
	{
		"path": "move.compensation.file"
	},
	{
		"path": "move.compensation.liveGrid"
	},
	{
		"path": "move.compensation.liveGrid.axes"
	},
	{
		"path": "move.compensation.liveGrid.maxs"
	},
	{
		"path": "move.compensation.liveGrid.mins"
	},
	{
		"path": "move.compensation.liveGrid.radius"
	},
	{
		"path": "move.compensation.liveGrid.spacings"
	},
	{
		"path": "move.compensation.meshDeviation"
	},
	{
		"path": "move.compensation.meshDeviation.deviation"
	},
	{
		"path": "move.compensation.meshDeviation.mean"
	},
	{
		"path": "move.compensation.probeGrid"
	},
	{
		"path": "move.compensation.probeGrid.axes"
	},
	{
		"path": "move.compensation.probeGrid.maxs"
	},
	{
		"path": "move.compensation.probeGrid.mins"
	},
	{
		"path": "move.compensation.probeGrid.radius"
	},
	{
		"path": "move.compensation.probeGrid.spacings"
	},
	{
		"path": "move.compensation.skew"
	},
	{
		"path": "move.compensation.skew.compensateXY"
	},
	{
		"path": "move.compensation.skew.tanXY"
	},
	{
		"path": "move.compensation.skew.tanXZ"
	},
	{
		"path": "move.compensation.skew.tanYZ"
	},
	{
		"path": "move.compensation.type"
	},
	{
		"path": "move.currentMove"
	},
	{
		"path": "move.currentMove.acceleration"
	},
	{
		"path": "move.currentMove.deceleration"
	},
	{
		"path": "move.currentMove.distance",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.currentMove.duration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.currentMove.extrusionRate"
	},
	{
		"path": "move.currentMove.filePosition",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "move.currentMove.laserPwm"
	},
	{
		"path": "move.currentMove.requestedSpeed"
	},
	{
		"path": "move.currentMove.topSpeed"
	},
	{
		"path": "move.extruders"
	},
	{
		"path": "move.extruders[].acceleration"
	},
	{
		"path": "move.extruders[].current"
	},
	{
		"path": "move.extruders[].driver"
	},
	{
		"path": "move.extruders[].factor"
	},
	{
		"path": "move.extruders[].filament"
	},
	{
		"path": "move.extruders[].filamentDiameter"
	},
	{
		"path": "move.extruders[].jerk"
	},
	{
		"path": "move.extruders[].microstepping"
	},
	{
		"path": "move.extruders[].microstepping.interpolated"
	},
	{
		"path": "move.extruders[].microstepping.value"
	},
	{
		"path": "move.extruders[].nonlinear"
	},
	{
		"path": "move.extruders[].nonlinear.a"
	},
	{
		"path": "move.extruders[].nonlinear.b"
	},
	{
		"path": "move.extruders[].nonlinear.upperLimit"
	},
	{
		"path": "move.extruders[].percentCurrent"
	},
	{
		"path": "move.extruders[].percentStstCurrent"
	},
	{
		"path": "move.extruders[].phaseStep"
	},
	{
		"path": "move.extruders[].position"
	},
	{
		"path": "move.extruders[].pressAdv",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.d",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.k0",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.k1",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressureAdvance",
		"deprecated": {
			"since": "3.6.3",
			"message": "use pressAdv.k0 instead"
		}
	},
	{
		"path": "move.extruders[].printingJerk"
	},
	{
		"path": "move.extruders[].rawPosition"
	},
	{
		"path": "move.extruders[].speed"
	},
	{
		"path": "move.extruders[].stepsPerMm"
	},
	{
		"path": "move.idle"
	},
	{
		"path": "move.idle.factor"
	},
	{
		"path": "move.idle.timeout"
	},
	{
		"path": "move.keepout"
	},
	{
		"path": "move.keepout[].active",
		"until": "3.6.3"
	},
	{
		"path": "move.keepout[].coords",
		"until": "3.6.3"
	},
	{
		"path": "move.keepout[].coords[].max"
	},
	{
		"path": "move.keepout[].coords[].min"
	},
	{
		"path": "move.kinematics"
	},
	{
		"path": "move.kinematics.anchors"
	},
	{
		"path": "move.kinematics.crosstalk"
	},
	{
		"path": "move.kinematics.deltaRadius"
	},
	{
		"path": "move.kinematics.distalLength"
	},
	{
		"path": "move.kinematics.forwardMatrix"
	},
	{
		"path": "move.kinematics.homedHeight"
	},
	{
		"path": "move.kinematics.inverseMatrix"
	},
	{
		"path": "move.kinematics.minRadius"
	},
	{
		"path": "move.kinematics.name"
	},
	{
		"path": "move.kinematics.printRadius"
	},
	{
		"path": "move.kinematics.proximalLength"
	},
	{
		"path": "move.kinematics.psiLimits"
	},
	{
		"path": "move.kinematics.radiusHomed"
	},
	{
		"path": "move.kinematics.radiusMax"
	},
	{
		"path": "move.kinematics.radiusMin"
	},
	{
		"path": "move.kinematics.segmentation"
	},
	{
		"path": "move.kinematics.segmentation.minSegLength"
	},
	{
		"path": "move.kinematics.segmentation.segmentsPerSec"
	},
	{
		"path": "move.kinematics.thetaLimits"
	},
	{
		"path": "move.kinematics.tiltCorrection"
	},
	{
		"path": "move.kinematics.tiltCorrection.correctionFactor"
	},
	{
		"path": "move.kinematics.tiltCorrection.lastCorrections"
	},
	{
		"path": "move.kinematics.tiltCorrection.maxCorrection"
	},
	{
		"path": "move.kinematics.tiltCorrection.screwPitch"
	},
	{
		"path": "move.kinematics.tiltCorrection.screwX"
	},
	{
		"path": "move.kinematics.tiltCorrection.screwY"
	},
	{
		"path": "move.kinematics.towers"
	},
	{
		"path": "move.kinematics.towers[].angleCorrection"
	},
	{
		"path": "move.kinematics.towers[].diagonal"
	},
	{
		"path": "move.kinematics.towers[].endstopAdjustment"
	},
	{
		"path": "move.kinematics.towers[].xPos"
	},
	{
		"path": "move.kinematics.towers[].yPos"
	},
	{
		"path": "move.kinematics.ttAccMax"
	},
	{
		"path": "move.kinematics.ttSpeedMax"
	},
	{
		"path": "move.kinematics.xOffset"
	},
	{
		"path": "move.kinematics.xTilt"
	},
	{
		"path": "move.kinematics.yOffset"
	},
	{
		"path": "move.kinematics.yTilt"
	},
	{
		"path": "move.limitAxes"
	},
	{
		"path": "move.minSpeed",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "move.motionSystems",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.acceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.deceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.distance",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.duration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.extrusionRate",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.filePosition",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "move.motionSystems[].currentMove.laserPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.requestedSpeed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.topSpeed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentObject",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].nextTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].previousTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].printingAcceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].coords",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].extruderPos",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].fanPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].feedRate",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].gCommandNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].ioBits",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].laserPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].toolNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation.angle",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation.centre",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].speedFactor",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].travelAcceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].userPosition",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].virtualEPos",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].workplaceNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.noMovesBeforeHoming"
	},
	{
		"path": "move.printingAcceleration",
		"deprecated": {
			"since": "3.6.3",
			"message": "use motionSystems[].printingAcceleration instead"
		}
	},
	{
		"path": "move.queue"
	},
	{
		"path": "move.queue[].gracePeriod"
	},
	{
		"path": "move.queue[].length"
	},
	{
		"path": "move.rotation",
		"deprecated": {
			"since": "3.6.3",
			"message": "use motionSystems[].rotation instead"
		}
	},
	{
		"path": "move.rotation.angle"
	},
	{
		"path": "move.rotation.centre"
	},
	{
		"path": "move.shaping"
	},
	{
		"path": "move.shaping.amplitudes"
	},
	{
		"path": "move.shaping.damping"
	},
	{
		"path": "move.shaping.delays"
	},
	{
		"path": "move.shaping.frequency"
	},
	{
		"path": "move.shaping.type"
	},
	{
		"path": "move.speedFactor"
	},
	{
		"path": "move.travelAcceleration",
		"deprecated": {
			"since": "3.6.3",
			"message": "use motionSystems[].travelAcceleration instead"
		}
	},
	{
		"path": "move.usingSCurve"
	},
	{
		"path": "move.virtualEPos",
		"deprecated": {
			"since": "3.6.3",
			"message": "use motionSystems[].virtualEPos instead"
		}
	},
	{
		"path": "move.workplaceNumber",
		"deprecated": {
			"since": "3.6.3",
			"message": "use motionSystems[].workplaceNumber instead"
		}
	},
	{
		"path": "network"
	},
	{
		"path": "network.corsSite"
	},
	{
		"path": "network.hostname"
	},
	{
		"path": "network.interfaces"
	},
	{
		"path": "network.interfaces[].activeProtocols"
	},
	{
		"path": "network.interfaces[].actualIP"
	},
	{
		"path": "network.interfaces[].configuredIP"
	},
	{
		"path": "network.interfaces[].dnsServer"
	},
	{
		"path": "network.interfaces[].firmwareVersion"
	},
	{
		"path": "network.interfaces[].gateway"
	},
	{
		"path": "network.interfaces[].mac"
	},
	{
		"path": "network.interfaces[].numReconnects",
		"until": "3.6.3"
	},
	{
		"path": "network.interfaces[].rssi"
	},
	{
		"path": "network.interfaces[].signal",
		"deprecated": {
			"since": "3.6.3",
			"message": "use rssi instead"
		}
	},
	{
		"path": "network.interfaces[].speed"
	},
	{
		"path": "network.interfaces[].ssid"
	},
	{
		"path": "network.interfaces[].state"
	},
	{
		"path": "network.interfaces[].subnet"
	},
	{
		"path": "network.interfaces[].type"
	},
	{
		"path": "network.interfaces[].wifiCountry"
	},
	{
		"path": "network.name"
	},
	{
		"path": "plugins"
	},
	{
		"path": "plugins[].author"
	},
	{
		"path": "plugins[].data"
	},
	{
		"path": "plugins[].dsfFiles"
	},
	{
		"path": "plugins[].dwcDependencies"
	},
	{
		"path": "plugins[].dwcFiles"
	},
	{
		"path": "plugins[].dwcVersion"
	},
	{
		"path": "plugins[].homepage"
	},
	{
		"path": "plugins[].id"
	},
	{
		"path": "plugins[].license"
	},
	{
		"path": "plugins[].name"
	},
	{
		"path": "plugins[].pid"
	},
	{
		"path": "plugins[].rrfVersion"
	},
	{
		"path": "plugins[].sbcAutoRestart"
	},
	{
		"path": "plugins[].sbcConfigFiles"
	},
	{
		"path": "plugins[].sbcDsfVersion"
	},
	{
		"path": "plugins[].sbcExecutable"
	},
	{
		"path": "plugins[].sbcExecutableArguments"
	},
	{
		"path": "plugins[].sbcExtraExecutables"
	},
	{
		"path": "plugins[].sbcNotifyStarted",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "plugins[].sbcOutputRedirected"
	},
	{
		"path": "plugins[].sbcPackageDependencies"
	},
	{
		"path": "plugins[].sbcPermissions"
	},
	{
		"path": "plugins[].sbcPluginDependencies"
	},
	{
		"path": "plugins[].sbcPythonDependencies"
	},
	{
		"path": "plugins[].sbcRequired"
	},
	{
		"path": "plugins[].sdFiles"
	},
	{
		"path": "plugins[].started",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "plugins[].tags"
	},
	{
		"path": "plugins[].version"
	},
	{
		"path": "sbc"
	},
	{
		"path": "sbc.appArmor"
	},
	{
		"path": "sbc.cpu"
	},
	{
		"path": "sbc.cpu.avgLoad"
	},
	{
		"path": "sbc.cpu.hardware"
	},
	{
		"path": "sbc.cpu.numCores"
	},
	{
		"path": "sbc.cpu.temperature"
	},
	{
		"path": "sbc.distribution"
	},
	{
		"path": "sbc.distributionBuildTime"
	},
	{
		"path": "sbc.dsf"
	},
	{
		"path": "sbc.dsf.buildDateTime"
	},
	{
		"path": "sbc.dsf.communicationMethod",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "sbc.dsf.httpEndpoints"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].endpointType"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].isUploadRequest"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].namespace"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].path"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].unixSocket"
	},
	{
		"path": "sbc.dsf.is64Bit"
	},
	{
		"path": "sbc.dsf.pluginSupport"
	},
	{
		"path": "sbc.dsf.rootPluginSupport"
	},
	{
		"path": "sbc.dsf.userSessions"
	},
	{
		"path": "sbc.dsf.userSessions[].accessLevel"
	},
	{
		"path": "sbc.dsf.userSessions[].id"
	},
	{
		"path": "sbc.dsf.userSessions[].origin"
	},
	{
		"path": "sbc.dsf.userSessions[].originId"
	},
	{
		"path": "sbc.dsf.userSessions[].sessionType"
	},
	{
		"path": "sbc.dsf.version"
	},
	{
		"path": "sbc.memory"
	},
	{
		"path": "sbc.memory.available"
	},
	{
		"path": "sbc.memory.total"
	},
	{
		"path": "sbc.model"
	},
	{
		"path": "sbc.serial"
	},
	{
		"path": "sbc.upgrade",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.upgrade.message",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.upgrade.progress",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.uptime"
	},
	{
		"path": "sensors"
	},
	{
		"path": "sensors.analog"
	},
	{
		"path": "sensors.analog[].beta"
	},
	{
		"path": "sensors.analog[].c"
	},
	{
		"path": "sensors.analog[].highReading"
	},
	{
		"path": "sensors.analog[].lastReading"
	},
	{
		"path": "sensors.analog[].lowReading"
	},
	{
		"path": "sensors.analog[].name"
	},
	{
		"path": "sensors.analog[].offsetAdj"
	},
	{
		"path": "sensors.analog[].port"
	},
	{
		"path": "sensors.analog[].r25"
	},
	{
		"path": "sensors.analog[].rRef"
	},
	{
		"path": "sensors.analog[].slopeAdj"
	},
	{
		"path": "sensors.analog[].state"
	},
	{
		"path": "sensors.analog[].type"
	},
	{
		"path": "sensors.endstops"
	},
	{
		"path": "sensors.endstops[].highEnd"
	},
	{
		"path": "sensors.endstops[].probe"
	},
	{
		"path": "sensors.endstops[].triggered"
	},
	{
		"path": "sensors.endstops[].type"
	},
	{
		"path": "sensors.filamentMonitors"
	},
	{
		"path": "sensors.filamentMonitors[].agc",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.filamentMonitors[].avgPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.mmPerPulse"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.mmPerRev"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.percentMax"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.percentMin"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.sensitivity"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.totalDistance"
	},
	{
		"path": "sensors.filamentMonitors[].configured"
	},
	{
		"path": "sensors.filamentMonitors[].configured.allMoves"
	},
	{
		"path": "sensors.filamentMonitors[].configured.calibrationFactor"
	},
	{
		"path": "sensors.filamentMonitors[].configured.mmPerPulse"
	},
	{
		"path": "sensors.filamentMonitors[].configured.mmPerRev"
	},
	{
		"path": "sensors.filamentMonitors[].configured.percentMax"
	},
	{
		"path": "sensors.filamentMonitors[].configured.percentMin"
	},
	{
		"path": "sensors.filamentMonitors[].configured.sampleDistance"
	},
	{
		"path": "sensors.filamentMonitors[].enableMode"
	},
	{
		"path": "sensors.filamentMonitors[].enabled",
		"deprecated": {
			"since": "3.6.3",
			"message": "use enableMode instead"
		}
	},
	{
		"path": "sensors.filamentMonitors[].filamentPresent",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.filamentMonitors[].lastPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].maxPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].minPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].position"
	},
	{
		"path": "sensors.filamentMonitors[].status"
	},
	{
		"path": "sensors.filamentMonitors[].totalExtrusion"
	},
	{
		"path": "sensors.filamentMonitors[].type"
	},
	{
		"path": "sensors.gpIn"
	},
	{
		"path": "sensors.gpIn[].value"
	},
	{
		"path": "sensors.probes"
	},
	{
		"path": "sensors.probes[].calibA",
		"until": "3.6.3"
	},
	{
		"path": "sensors.probes[].calibB",
		"until": "3.6.3"
	},
	{
		"path": "sensors.probes[].calibrationTemperature"
	},
	{
		"path": "sensors.probes[].deployedByUser"
	},
	{
		"path": "sensors.probes[].disablesHeaters"
	},
	{
		"path": "sensors.probes[].diveHeight",
		"deprecated": {
			"since": "3.6.3",
			"message": "use diveHeights[0] instead"
		}
	},
	{
		"path": "sensors.probes[].diveHeights"
	},
	{
		"path": "sensors.probes[].isCalibrated"
	},
	{
		"path": "sensors.probes[].lastStopHeight"
	},
	{
		"path": "sensors.probes[].loadCell",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.probes[].loadCell.force",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.probes[].loadCell.gramsPerCount",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.probes[].loadCell.preload",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.probes[].loadCell.preloadWindow",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "sensors.probes[].maxProbeCount"
	},
	{
		"path": "sensors.probes[].measuredHeight"
	},
	{
		"path": "sensors.probes[].offsets"
	},
	{
		"path": "sensors.probes[].recoveryTime"
	},
	{
		"path": "sensors.probes[].scanCoefficients"
	},
	{
		"path": "sensors.probes[].speeds"
	},
	{
		"path": "sensors.probes[].temperatureCoefficients"
	},
	{
		"path": "sensors.probes[].threshold"
	},
	{
		"path": "sensors.probes[].tolerance"
	},
	{
		"path": "sensors.probes[].touchMode"
	},
	{
		"path": "sensors.probes[].touchMode.active"
	},
	{
		"path": "sensors.probes[].touchMode.sensitivity",
		"until": "3.6.3"
	},
	{
		"path": "sensors.probes[].touchMode.speed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "sensors.probes[].touchMode.threshold"
	},
	{
		"path": "sensors.probes[].touchMode.triggerHeight"
	},
	{
		"path": "sensors.probes[].travelSpeed"
	},
	{
		"path": "sensors.probes[].triggerHeight"
	},
	{
		"path": "sensors.probes[].type"
	},
	{
		"path": "sensors.probes[].value"
	},
	{
		"path": "spindles"
	},
	{
		"path": "spindles[].active"
	},
	{
		"path": "spindles[].canReverse"
	},
	{
		"path": "spindles[].current"
	},
	{
		"path": "spindles[].frequency"
	},
	{
		"path": "spindles[].idlePwm"
	},
	{
		"path": "spindles[].max"
	},
	{
		"path": "spindles[].maxPwm"
	},
	{
		"path": "spindles[].min"
	},
	{
		"path": "spindles[].minPwm"
	},
	{
		"path": "spindles[].state"
	},
	{
		"path": "spindles[].type"
	},
	{
		"path": "state"
	},
	{
		"path": "state.atxPower"
	},
	{
		"path": "state.atxPowerPort"
	},
	{
		"path": "state.beep"
	},
	{
		"path": "state.beep.duration"
	},
	{
		"path": "state.beep.frequency"
	},
	{
		"path": "state.currentTool"
	},
	{
		"path": "state.deferredPowerDown"
	},
	{
		"path": "state.displayMessage"
	},
	{
		"path": "state.gpOut"
	},
	{
		"path": "state.gpOut[].freq"
	},
	{
		"path": "state.gpOut[].pwm"
	},
	{
		"path": "state.laserPwm"
	},
	{
		"path": "state.logFile"
	},
	{
		"path": "state.logLevel"
	},
	{
		"path": "state.machineMode"
	},
	{
		"path": "state.macroRestarted"
	},
	{
		"path": "state.messageBox"
	},
	{
		"path": "state.messageBox.axisControls"
	},
	{
		"path": "state.messageBox.cancelButton"
	},
	{
		"path": "state.messageBox.choices"
	},
	{
		"path": "state.messageBox.default"
	},
	{
		"path": "state.messageBox.max"
	},
	{
		"path": "state.messageBox.message"
	},
	{
		"path": "state.messageBox.min"
	},
	{
		"path": "state.messageBox.mode"
	},
	{
		"path": "state.messageBox.seq"
	},
	{
		"path": "state.messageBox.timeout"
	},
	{
		"path": "state.messageBox.title"
	},
	{
		"path": "state.msUpTime"
	},
	{
		"path": "state.nextTool",
		"deprecated": {
			"since": "3.6.3",
			"message": "use move.motionSystems[].nextTool instead"
		}
	},
	{
		"path": "state.pluginsStarted"
	},
	{
		"path": "state.powerFailScript"
	},
	{
		"path": "state.previousTool",
		"deprecated": {
			"since": "3.6.3",
			"message": "use move.motionSystems[].previousTool instead"
		}
	},
	{
		"path": "state.restorePoints",
		"deprecated": {
			"since": "3.6.3",
			"message": "use move.motionSystems[].restorePoints instead"
		}
	},
	{
		"path": "state.restorePoints[].coords"
	},
	{
		"path": "state.restorePoints[].extruderPos"
	},
	{
		"path": "state.restorePoints[].fanPwm"
	},
	{
		"path": "state.restorePoints[].feedRate"
	},
	{
		"path": "state.restorePoints[].gCommandNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "state.restorePoints[].ioBits"
	},
	{
		"path": "state.restorePoints[].laserPwm"
	},
	{
		"path": "state.restorePoints[].toolNumber"
	},
	{
		"path": "state.startupError"
	},
	{
		"path": "state.startupError.file"
	},
	{
		"path": "state.startupError.line"
	},
	{
		"path": "state.startupError.message"
	},
	{
		"path": "state.status"
	},
	{
		"path": "state.thisActive",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "state.thisInput"
	},
	{
		"path": "state.time"
	},
	{
		"path": "state.upTime"
	},
	{
		"path": "tools"
	},
	{
		"path": "tools[].active"
	},
	{
		"path": "tools[].axes"
	},
	{
		"path": "tools[].extruders"
	},
	{
		"path": "tools[].fans"
	},
	{
		"path": "tools[].feedForward",
		"deprecated": {
			"since": "3.6.3",
			"message": "use feedForwardPwm instead"
		}
	},
	{
		"path": "tools[].feedForwardAdvance"
	},
	{
		"path": "tools[].feedForwardPwm"
	},
	{
		"path": "tools[].feedForwardTemp"
	},
	{
		"path": "tools[].filamentExtruder"
	},
	{
		"path": "tools[].heaters"
	},
	{
		"path": "tools[].isRetracted"
	},
	{
		"path": "tools[].mix"
	},
	{
		"path": "tools[].name"
	},
	{
		"path": "tools[].number"
	},
	{
		"path": "tools[].offsets"
	},
	{
		"path": "tools[].offsetsProbed"
	},
	{
		"path": "tools[].retraction"
	},
	{
		"path": "tools[].retraction.extraRestart"
	},
	{
		"path": "tools[].retraction.length"
	},
	{
		"path": "tools[].retraction.speed"
	},
	{
		"path": "tools[].retraction.unretractSpeed"
	},
	{
		"path": "tools[].retraction.zHop"
	},
	{
		"path": "tools[].spindle"
	},
	{
		"path": "tools[].spindleRpm"
	},
	{
		"path": "tools[].standby"
	},
	{
		"path": "tools[].state"
	},
	{
		"path": "volumes"
	},
	{
		"path": "volumes[].capacity"
	},
	{
		"path": "volumes[].freeSpace"
	},
	{
		"path": "volumes[].mounted"
	},
	{
		"path": "volumes[].name"
	},
	{
		"path": "volumes[].openFiles"
	},
	{
		"path": "volumes[].partitionSize",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "volumes[].path"
	},
	{
		"path": "volumes[].speed"
	}
];
const PATHS = OBJECT_MODEL_PATHS;

const BY_PATH: ReadonlyMap<string, ObjectModelPathEntry> = new Map(PATHS.map((e) => [e.path, e]));
const TRACKED_ORDER: ReadonlyArray<string> = ["3.6.3","3.7.0-beta.1","3.7.0-beta.2","3.7.0-beta.3","3.7.0-rc.1"];

function trackedIndex(version: string): number {
	const i = TRACKED_ORDER.indexOf(version);
	if (i === -1) {
		const known = OBJECT_MODEL_VERSIONS.find((v) => v.version === version);
		throw new Error(
			known === undefined
				? `"${version}" is not one of OBJECT_MODEL_VERSIONS`
				: `"${version}" has no object-model data (OBJECT_MODEL_VERSIONS reports hasData: false)`,
		);
	}
	return i;
}

export interface ObjectModelPathStatus {
	known: boolean;
	deprecated?: string;
	since?: string;
	until?: string;
}

/** Whether `path` (already normalised - `[]` for every array/dictionary index, as task 07's
 *  expression-path handling already produces) is part of the object model at `rrfVersion`, and
 *  whether/since-when it's deprecated. Throws if `rrfVersion` isn't one of OBJECT_MODEL_VERSIONS or
 *  has no tracked data (see ObjectModelVersionInfo.hasData). */
export function objectModelPath(path: string, rrfVersion: string): ObjectModelPathStatus {
	const versionIndex = trackedIndex(rrfVersion);
	const entry = BY_PATH.get(path);
	if (entry === undefined) return { known: false };
	const sinceIndex = entry.since === undefined ? 0 : trackedIndex(entry.since);
	const untilIndex = entry.until === undefined ? TRACKED_ORDER.length - 1 : trackedIndex(entry.until);
	const known = versionIndex >= sinceIndex && versionIndex <= untilIndex;
	if (!known) return { known: false };
	const result: ObjectModelPathStatus = { known: true };
	if (entry.since !== undefined) result.since = entry.since;
	if (entry.until !== undefined) result.until = entry.until;
	if (entry.deprecated !== undefined && trackedIndex(entry.deprecated.since) <= versionIndex) {
		result.deprecated = entry.deprecated.message;
	}
	return result;
}

export interface ObjectModelChange {
	path: string;
	change: "added" | "removed" | "deprecated";
	version: string;
}

/** Every object-model path change between two tracked versions, in the direction actually given -
 *  a downgrade (`toVersion` older than `fromVersion`) reports each addition going forward as a
 *  "removed" and each removal going forward as an "added", so the result always describes what
 *  changes moving from `fromVersion` to `toVersion`, whichever way that runs. */
export function objectModelChanges(fromVersion: string, toVersion: string): ReadonlyArray<ObjectModelChange> {
	const fromIndex = trackedIndex(fromVersion);
	const toIndex = trackedIndex(toVersion);
	const forward = toIndex >= fromIndex;
	const [lo, hi] = forward ? [fromIndex, toIndex] : [toIndex, fromIndex];
	const changes: Array<ObjectModelChange> = [];
	for (const entry of PATHS) {
		const sinceIndex = entry.since === undefined ? 0 : trackedIndex(entry.since);
		const untilIndex = entry.until === undefined ? TRACKED_ORDER.length - 1 : trackedIndex(entry.until);
		const presentAtLo = sinceIndex <= lo && lo <= untilIndex;
		const presentAtHi = sinceIndex <= hi && hi <= untilIndex;
		// The reported "version" is always the actual RRF version the underlying transition happened
		// at (entry.since/entry.until - always defined in these branches, since an undefined since
		// means "present from the very first tracked version", which would make presentAtLo true) -
		// direction only flips which LABEL ("added" vs "removed") that same transition gets, not
		// where it's pinned. Pinning it to a range endpoint instead (an earlier version of this
		// function did exactly that) reports the wrong version for every downgrade comparison whose
		// range doesn't start/end exactly on the transition itself.
		if (!presentAtLo && presentAtHi) {
			changes.push({ path: entry.path, change: forward ? "added" : "removed", version: entry.since ?? TRACKED_ORDER[lo] });
		} else if (presentAtLo && !presentAtHi) {
			changes.push({ path: entry.path, change: forward ? "removed" : "added", version: entry.until ?? TRACKED_ORDER[hi] });
		}
		if (entry.deprecated !== undefined) {
			const depIndex = trackedIndex(entry.deprecated.since);
			if (depIndex > lo && depIndex <= hi) {
				changes.push({ path: entry.path, change: "deprecated", version: entry.deprecated.since });
			}
		}
	}
	return changes.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
