/**
 * Object-model path existence/deprecation per RRF release (task 11, docs/tasks/11-object-model-schema.md).
 * GENERATED by scripts/build-om-schema.mjs - do not hand-edit; edit the generator and re-run it.
 * "since" omitted = present at the oldest tracked version ("3.6.3"); "until" omitted
 * = still present at the newest ("3.7.0-rc.2").
 */

import { OBJECT_MODEL_VERSIONS } from "./versions.js";

export interface ObjectModelPathEntry {
	path: string;
	since?: string;
	until?: string;
	/** source is set when the RRF source (not the mirror) decides the date - see RRF_OBSOLETE_FROM in scripts/build-om-schema.mjs. */
	deprecated?: { since: string; message: string; source?: string };
	/** How many times this path's own value can be indexed: 1 for an array, collection or dictionary
	 *  (`heat.heaters`, `sensors.probes[].offsets`), 2 for an array of arrays; omitted for anything that
	 *  isn't indexable. `objectModelPath` accepts `<path>[]` (and `<path>[][]`) up to this depth. */
	array?: number;
	/** Set only for a path RRF serves but the `@duet3d/objectmodel` package (documentation.json and the
	 *  TypeScript source alike) doesn't declare - the RRF source this was read from. */
	source?: string;
	/** Set on a path that stopped existing because RRF moved the data: where it went, in words a user
	 *  reading a "removed" finding can act on. */
	note?: string;
}

/** Every known path with its lifetime, exported so other generators (task 12's release-events store)
 *  can turn "path added/removed/deprecated at version X" straight into a ChangeEvent without
 *  re-deriving this data. */
export const OBJECT_MODEL_PATHS: ReadonlyArray<ObjectModelPathEntry> = [
	{
		"path": "boards",
		"array": 1
	},
	{
		"path": "boards[].accelerometer",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[] in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].accelerometer.orientation",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[].orientation in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].accelerometer.points",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[].points in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].accelerometer.resolution",
		"since": "3.7.0-rc.1",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[].resolution in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].accelerometer.runs",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[].runs in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].accelerometer.samplingRate",
		"since": "3.7.0-rc.1",
		"until": "3.7.0-rc.1",
		"note": "moved to sensors.accelerometers[].samplingRate in 3.7.0-rc.2 - index it by the M955/M956 P number (RRF commit 0ee0de8800; boards[0]'s entry, ExpansionManager.cpp:53,91 and Platform.cpp:215,282 at 3.7.0-rc.1, is gone)"
	},
	{
		"path": "boards[].bootloaderFileName",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "boards[].canAddress"
	},
	{
		"path": "boards[].closedLoop"
	},
	{
		"path": "boards[].closedLoop.points"
	},
	{
		"path": "boards[].closedLoop.runs"
	},
	{
		"path": "boards[].directDisplay"
	},
	{
		"path": "boards[].directDisplay.encoder"
	},
	{
		"path": "boards[].directDisplay.encoder.pulsesPerClick"
	},
	{
		"path": "boards[].directDisplay.screen"
	},
	{
		"path": "boards[].directDisplay.screen.colourBits"
	},
	{
		"path": "boards[].directDisplay.screen.contrast"
	},
	{
		"path": "boards[].directDisplay.screen.controller"
	},
	{
		"path": "boards[].directDisplay.screen.height"
	},
	{
		"path": "boards[].directDisplay.screen.resistorRatio"
	},
	{
		"path": "boards[].directDisplay.screen.spiFreq"
	},
	{
		"path": "boards[].directDisplay.screen.width"
	},
	{
		"path": "boards[].drivers",
		"array": 1
	},
	{
		"path": "boards[].drivers[].closedLoop"
	},
	{
		"path": "boards[].drivers[].closedLoop.currentFraction"
	},
	{
		"path": "boards[].drivers[].closedLoop.currentFraction.avg"
	},
	{
		"path": "boards[].drivers[].closedLoop.currentFraction.max"
	},
	{
		"path": "boards[].drivers[].closedLoop.positionError"
	},
	{
		"path": "boards[].drivers[].closedLoop.positionError.max"
	},
	{
		"path": "boards[].drivers[].closedLoop.positionError.rms"
	},
	{
		"path": "boards[].drivers[].config",
		"since": "3.7.0-beta.1",
		"source": "RRF 3.7.0-beta.1 Movement/StepperDrivers/DriverData.cpp:22 DriverData::objectModelTable - { \"config\", OBJECT_MODEL_FUNC(self, 4) } with its direction and mode members (RRF commit 0bfca0e98 \"Added driver mode and direction setting and DriverData and object model\"); the mirror lists config.direction and config.mode from beta.1 but the container only from rc.1"
	},
	{
		"path": "boards[].drivers[].config.direction",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "boards[].drivers[].config.mode",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "boards[].drivers[].status"
	},
	{
		"path": "boards[].firmwareDate"
	},
	{
		"path": "boards[].firmwareFileName"
	},
	{
		"path": "boards[].firmwareName"
	},
	{
		"path": "boards[].firmwareVersion"
	},
	{
		"path": "boards[].freeRam"
	},
	{
		"path": "boards[].iapFileNameSBC"
	},
	{
		"path": "boards[].iapFileNameSD"
	},
	{
		"path": "boards[].inductiveSensor"
	},
	{
		"path": "boards[].maxHeaters"
	},
	{
		"path": "boards[].maxMotors"
	},
	{
		"path": "boards[].mcuTemp"
	},
	{
		"path": "boards[].mcuTemp.current"
	},
	{
		"path": "boards[].mcuTemp.max"
	},
	{
		"path": "boards[].mcuTemp.min"
	},
	{
		"path": "boards[].name"
	},
	{
		"path": "boards[].shortName"
	},
	{
		"path": "boards[].state"
	},
	{
		"path": "boards[].supportsDirectDisplay"
	},
	{
		"path": "boards[].timeout",
		"since": "3.7.0-beta.2",
		"source": "RRF 3.7.0-beta.2 CAN/ExpansionManager.cpp:66 ExpansionManager::objectModelTable - { \"timeout\" } (RRF commit e77b50a1e \"Implemented #858\"); absent from the 3.7.0-beta.1 tag"
	},
	{
		"path": "boards[].uniqueId"
	},
	{
		"path": "boards[].v12"
	},
	{
		"path": "boards[].v12.current"
	},
	{
		"path": "boards[].v12.max"
	},
	{
		"path": "boards[].v12.min"
	},
	{
		"path": "boards[].vIn"
	},
	{
		"path": "boards[].vIn.current"
	},
	{
		"path": "boards[].vIn.max"
	},
	{
		"path": "boards[].vIn.min"
	},
	{
		"path": "boards[].wifiFirmwareFileName"
	},
	{
		"path": "directories"
	},
	{
		"path": "directories.filaments"
	},
	{
		"path": "directories.firmware"
	},
	{
		"path": "directories.gCodes"
	},
	{
		"path": "directories.macros"
	},
	{
		"path": "directories.menu"
	},
	{
		"path": "directories.system"
	},
	{
		"path": "directories.web"
	},
	{
		"path": "fans",
		"array": 1
	},
	{
		"path": "fans[].actualValue"
	},
	{
		"path": "fans[].blip"
	},
	{
		"path": "fans[].frequency"
	},
	{
		"path": "fans[].max"
	},
	{
		"path": "fans[].min"
	},
	{
		"path": "fans[].name"
	},
	{
		"path": "fans[].requestedValue"
	},
	{
		"path": "fans[].rpm"
	},
	{
		"path": "fans[].tachoPpr"
	},
	{
		"path": "fans[].thermostatic"
	},
	{
		"path": "fans[].thermostatic.heaters",
		"until": "3.7.0-alpha.2",
		"array": 1
	},
	{
		"path": "fans[].thermostatic.highTemperature"
	},
	{
		"path": "fans[].thermostatic.lowTemperature"
	},
	{
		"path": "fans[].thermostatic.sensors",
		"array": 1
	},
	{
		"path": "global",
		"array": 1
	},
	{
		"path": "heat"
	},
	{
		"path": "heat.bedHeaterMapping",
		"since": "3.7.0-beta.1",
		"array": 2
	},
	{
		"path": "heat.bedHeaters",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use bedHeaterMapping instead",
			"source": "RRF 3.7.0-beta.1 Heating/Heat.cpp:141 - ObjectModelEntryFlags::obsolete (RRF 8a1738d02, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		},
		"array": 1
	},
	{
		"path": "heat.chamberHeaterMapping",
		"since": "3.7.0-beta.1",
		"array": 2
	},
	{
		"path": "heat.chamberHeaters",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use chamberHeaterMapping instead",
			"source": "RRF 3.7.0-beta.1 Heating/Heat.cpp:143 - ObjectModelEntryFlags::obsolete (RRF 8a1738d02, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		},
		"array": 1
	},
	{
		"path": "heat.coldExtrudeTemperature"
	},
	{
		"path": "heat.coldRetractTemperature"
	},
	{
		"path": "heat.heaters",
		"array": 1
	},
	{
		"path": "heat.heaters[].active"
	},
	{
		"path": "heat.heaters[].avgPwm"
	},
	{
		"path": "heat.heaters[].current"
	},
	{
		"path": "heat.heaters[].extrPwmBoost"
	},
	{
		"path": "heat.heaters[].extrTempBoost"
	},
	{
		"path": "heat.heaters[].max"
	},
	{
		"path": "heat.heaters[].maxBadReadings"
	},
	{
		"path": "heat.heaters[].maxHeatingFaultTime"
	},
	{
		"path": "heat.heaters[].maxTempExcursion"
	},
	{
		"path": "heat.heaters[].min"
	},
	{
		"path": "heat.heaters[].model"
	},
	{
		"path": "heat.heaters[].model.coolingExp"
	},
	{
		"path": "heat.heaters[].model.coolingRate"
	},
	{
		"path": "heat.heaters[].model.deadTime"
	},
	{
		"path": "heat.heaters[].model.enabled"
	},
	{
		"path": "heat.heaters[].model.fanCoolingRate"
	},
	{
		"path": "heat.heaters[].model.heatingRate"
	},
	{
		"path": "heat.heaters[].model.inverted"
	},
	{
		"path": "heat.heaters[].model.maxPwm"
	},
	{
		"path": "heat.heaters[].model.pid"
	},
	{
		"path": "heat.heaters[].model.pid.d"
	},
	{
		"path": "heat.heaters[].model.pid.i"
	},
	{
		"path": "heat.heaters[].model.pid.overridden",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "heat.heaters[].model.pid.p"
	},
	{
		"path": "heat.heaters[].model.pid.used"
	},
	{
		"path": "heat.heaters[].model.standardVoltage"
	},
	{
		"path": "heat.heaters[].monitors",
		"array": 1
	},
	{
		"path": "heat.heaters[].monitors[].action"
	},
	{
		"path": "heat.heaters[].monitors[].condition"
	},
	{
		"path": "heat.heaters[].monitors[].limit"
	},
	{
		"path": "heat.heaters[].monitors[].sensor"
	},
	{
		"path": "heat.heaters[].sensor"
	},
	{
		"path": "heat.heaters[].standby"
	},
	{
		"path": "heat.heaters[].state"
	},
	{
		"path": "inputs",
		"array": 1
	},
	{
		"path": "inputs[].active"
	},
	{
		"path": "inputs[].axesRelative"
	},
	{
		"path": "inputs[].compatibility"
	},
	{
		"path": "inputs[].currentFile",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "inputs[].distanceUnit"
	},
	{
		"path": "inputs[].drivesRelative"
	},
	{
		"path": "inputs[].feedRate"
	},
	{
		"path": "inputs[].inMacro"
	},
	{
		"path": "inputs[].inverseTimeMode",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "inputs[].lineNumber"
	},
	{
		"path": "inputs[].macroRestartable"
	},
	{
		"path": "inputs[].motionSystem"
	},
	{
		"path": "inputs[].name"
	},
	{
		"path": "inputs[].selectedPlane"
	},
	{
		"path": "inputs[].stackDepth"
	},
	{
		"path": "inputs[].state"
	},
	{
		"path": "inputs[].volumetric"
	},
	{
		"path": "job"
	},
	{
		"path": "job.build"
	},
	{
		"path": "job.build.currentObject"
	},
	{
		"path": "job.build.m486Names",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.build.m486Numbers",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.build.m486names",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "job.build.m486numbers",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "job.build.objects",
		"array": 1
	},
	{
		"path": "job.build.objects[].cancelled"
	},
	{
		"path": "job.build.objects[].name"
	},
	{
		"path": "job.build.objects[].x",
		"array": 1
	},
	{
		"path": "job.build.objects[].y",
		"array": 1
	},
	{
		"path": "job.duration"
	},
	{
		"path": "job.file"
	},
	{
		"path": "job.file.customInfo",
		"array": 1
	},
	{
		"path": "job.file.filament",
		"array": 1
	},
	{
		"path": "job.file.fileName"
	},
	{
		"path": "job.file.generatedBy"
	},
	{
		"path": "job.file.height"
	},
	{
		"path": "job.file.lastModified"
	},
	{
		"path": "job.file.layerHeight"
	},
	{
		"path": "job.file.numLayers"
	},
	{
		"path": "job.file.printTime"
	},
	{
		"path": "job.file.simulatedTime"
	},
	{
		"path": "job.file.size"
	},
	{
		"path": "job.file.thumbnails",
		"array": 1
	},
	{
		"path": "job.file.thumbnails[].data"
	},
	{
		"path": "job.file.thumbnails[].format"
	},
	{
		"path": "job.file.thumbnails[].height"
	},
	{
		"path": "job.file.thumbnails[].offset"
	},
	{
		"path": "job.file.thumbnails[].size"
	},
	{
		"path": "job.file.thumbnails[].width"
	},
	{
		"path": "job.filePosition"
	},
	{
		"path": "job.lastDuration"
	},
	{
		"path": "job.lastFileAborted"
	},
	{
		"path": "job.lastFileCancelled"
	},
	{
		"path": "job.lastFileName"
	},
	{
		"path": "job.lastFileSimulated"
	},
	{
		"path": "job.lastWarmUpDuration"
	},
	{
		"path": "job.layer"
	},
	{
		"path": "job.layerTime"
	},
	{
		"path": "job.layers",
		"array": 1
	},
	{
		"path": "job.layers[].duration"
	},
	{
		"path": "job.layers[].filament",
		"deprecated": {
			"since": "3.6.3",
			"message": "use filamentUsage instead"
		},
		"array": 1
	},
	{
		"path": "job.layers[].filamentUsage",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "job.layers[].fractionPrinted"
	},
	{
		"path": "job.layers[].height"
	},
	{
		"path": "job.layers[].temperatures",
		"array": 1
	},
	{
		"path": "job.pauseDuration"
	},
	{
		"path": "job.rawExtrusion"
	},
	{
		"path": "job.timesLeft"
	},
	{
		"path": "job.timesLeft.filament"
	},
	{
		"path": "job.timesLeft.file"
	},
	{
		"path": "job.timesLeft.slicer"
	},
	{
		"path": "job.timesLeft.toPause"
	},
	{
		"path": "job.warmUpDuration"
	},
	{
		"path": "ledStrips",
		"array": 1
	},
	{
		"path": "ledStrips[].board"
	},
	{
		"path": "ledStrips[].colorOrder",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "ledStrips[].maxLeds",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "ledStrips[].pin"
	},
	{
		"path": "ledStrips[].stopMovement"
	},
	{
		"path": "ledStrips[].type"
	},
	{
		"path": "limits"
	},
	{
		"path": "limits.axes"
	},
	{
		"path": "limits.axesPlusExtruders"
	},
	{
		"path": "limits.bedHeaters"
	},
	{
		"path": "limits.boards"
	},
	{
		"path": "limits.chamberHeaters"
	},
	{
		"path": "limits.drivers"
	},
	{
		"path": "limits.driversPerAxis"
	},
	{
		"path": "limits.extruders"
	},
	{
		"path": "limits.extrudersPerTool"
	},
	{
		"path": "limits.fans"
	},
	{
		"path": "limits.gpInPorts"
	},
	{
		"path": "limits.gpOutPorts"
	},
	{
		"path": "limits.heaters"
	},
	{
		"path": "limits.heatersPerTool"
	},
	{
		"path": "limits.ledStrips"
	},
	{
		"path": "limits.monitorsPerHeater"
	},
	{
		"path": "limits.portsPerHeater"
	},
	{
		"path": "limits.reportedAxes"
	},
	{
		"path": "limits.restorePoints"
	},
	{
		"path": "limits.sensors"
	},
	{
		"path": "limits.spindles"
	},
	{
		"path": "limits.tools"
	},
	{
		"path": "limits.trackedObjects"
	},
	{
		"path": "limits.triggers"
	},
	{
		"path": "limits.volumes"
	},
	{
		"path": "limits.workplaces"
	},
	{
		"path": "limits.zProbeProgramBytes"
	},
	{
		"path": "limits.zProbes"
	},
	{
		"path": "move"
	},
	{
		"path": "move.accelerationTime",
		"since": "3.7.0-alpha.2",
		"note": "RRF serves it from 3.7.0-alpha.2 (Movement/Move.cpp Move::objectModelTable, RRF bee83e350) on boards built with third-order motion control only; absent from RRF 3.6.3 although the Duet3D/ObjectModel v3.6.3 mirror declares it"
	},
	{
		"path": "move.axes",
		"array": 1
	},
	{
		"path": "move.axes[].acceleration"
	},
	{
		"path": "move.axes[].babystep"
	},
	{
		"path": "move.axes[].backlash"
	},
	{
		"path": "move.axes[].current"
	},
	{
		"path": "move.axes[].drivers",
		"array": 1
	},
	{
		"path": "move.axes[].homed"
	},
	{
		"path": "move.axes[].jerk"
	},
	{
		"path": "move.axes[].letter"
	},
	{
		"path": "move.axes[].machinePosition"
	},
	{
		"path": "move.axes[].max"
	},
	{
		"path": "move.axes[].maxProbed"
	},
	{
		"path": "move.axes[].microstepping"
	},
	{
		"path": "move.axes[].microstepping.interpolated"
	},
	{
		"path": "move.axes[].microstepping.value"
	},
	{
		"path": "move.axes[].min"
	},
	{
		"path": "move.axes[].minProbed"
	},
	{
		"path": "move.axes[].percentCurrent"
	},
	{
		"path": "move.axes[].percentStstCurrent"
	},
	{
		"path": "move.axes[].phaseStep"
	},
	{
		"path": "move.axes[].printingJerk"
	},
	{
		"path": "move.axes[].reducedAcceleration"
	},
	{
		"path": "move.axes[].speed"
	},
	{
		"path": "move.axes[].stepPos"
	},
	{
		"path": "move.axes[].stepsPerMm"
	},
	{
		"path": "move.axes[].userPosition"
	},
	{
		"path": "move.axes[].visible"
	},
	{
		"path": "move.axes[].workplaceOffsets",
		"array": 1
	},
	{
		"path": "move.backlashFactor"
	},
	{
		"path": "move.calibration"
	},
	{
		"path": "move.calibration.final"
	},
	{
		"path": "move.calibration.final.deviation"
	},
	{
		"path": "move.calibration.final.mean"
	},
	{
		"path": "move.calibration.initial"
	},
	{
		"path": "move.calibration.initial.deviation"
	},
	{
		"path": "move.calibration.initial.mean"
	},
	{
		"path": "move.calibration.numFactors"
	},
	{
		"path": "move.compensation"
	},
	{
		"path": "move.compensation.fadeHeight"
	},
	{
		"path": "move.compensation.file"
	},
	{
		"path": "move.compensation.liveGrid"
	},
	{
		"path": "move.compensation.liveGrid.axes",
		"array": 1
	},
	{
		"path": "move.compensation.liveGrid.maxs",
		"array": 1
	},
	{
		"path": "move.compensation.liveGrid.mins",
		"array": 1
	},
	{
		"path": "move.compensation.liveGrid.radius"
	},
	{
		"path": "move.compensation.liveGrid.spacings",
		"array": 1
	},
	{
		"path": "move.compensation.meshDeviation"
	},
	{
		"path": "move.compensation.meshDeviation.deviation"
	},
	{
		"path": "move.compensation.meshDeviation.mean"
	},
	{
		"path": "move.compensation.probeGrid"
	},
	{
		"path": "move.compensation.probeGrid.axes",
		"array": 1
	},
	{
		"path": "move.compensation.probeGrid.maxs",
		"array": 1
	},
	{
		"path": "move.compensation.probeGrid.mins",
		"array": 1
	},
	{
		"path": "move.compensation.probeGrid.radius"
	},
	{
		"path": "move.compensation.probeGrid.spacings",
		"array": 1
	},
	{
		"path": "move.compensation.skew"
	},
	{
		"path": "move.compensation.skew.compensateXY"
	},
	{
		"path": "move.compensation.skew.tanXY"
	},
	{
		"path": "move.compensation.skew.tanXZ"
	},
	{
		"path": "move.compensation.skew.tanYZ"
	},
	{
		"path": "move.compensation.type"
	},
	{
		"path": "move.currentMove"
	},
	{
		"path": "move.currentMove.acceleration"
	},
	{
		"path": "move.currentMove.deceleration"
	},
	{
		"path": "move.currentMove.distance",
		"since": "3.7.0-alpha.2"
	},
	{
		"path": "move.currentMove.duration",
		"since": "3.7.0-alpha.2"
	},
	{
		"path": "move.currentMove.extrusionRate"
	},
	{
		"path": "move.currentMove.filePosition",
		"since": "3.7.0-beta.2",
		"source": "RRF 3.7.0-beta.2 Movement/Move.cpp:213 Move::objectModelTable section 2 - { \"filePosition\" } (RRF commit c8bb141f3 \"Added move.currentMove.filePosition\"); the mirror lists it from rc.1"
	},
	{
		"path": "move.currentMove.laserPwm"
	},
	{
		"path": "move.currentMove.requestedSpeed"
	},
	{
		"path": "move.currentMove.topSpeed"
	},
	{
		"path": "move.extruders",
		"array": 1
	},
	{
		"path": "move.extruders[].acceleration"
	},
	{
		"path": "move.extruders[].current"
	},
	{
		"path": "move.extruders[].driver"
	},
	{
		"path": "move.extruders[].factor"
	},
	{
		"path": "move.extruders[].filament"
	},
	{
		"path": "move.extruders[].filamentDiameter"
	},
	{
		"path": "move.extruders[].jerk"
	},
	{
		"path": "move.extruders[].microstepping"
	},
	{
		"path": "move.extruders[].microstepping.interpolated"
	},
	{
		"path": "move.extruders[].microstepping.value"
	},
	{
		"path": "move.extruders[].nonlinear"
	},
	{
		"path": "move.extruders[].nonlinear.a"
	},
	{
		"path": "move.extruders[].nonlinear.b"
	},
	{
		"path": "move.extruders[].nonlinear.upperLimit"
	},
	{
		"path": "move.extruders[].percentCurrent"
	},
	{
		"path": "move.extruders[].percentStstCurrent"
	},
	{
		"path": "move.extruders[].phaseStep"
	},
	{
		"path": "move.extruders[].position"
	},
	{
		"path": "move.extruders[].pressAdv",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.d",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.k0",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressAdv.k1",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.extruders[].pressureAdvance",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use pressAdv.k0 instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:304 - ObjectModelEntryFlags::obsolete (RRF 3f76f7e1b, first in the 3.7.0-alpha.4 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "move.extruders[].printingJerk"
	},
	{
		"path": "move.extruders[].rawPosition"
	},
	{
		"path": "move.extruders[].speed"
	},
	{
		"path": "move.extruders[].stepsPerMm"
	},
	{
		"path": "move.idle"
	},
	{
		"path": "move.idle.factor"
	},
	{
		"path": "move.idle.timeout"
	},
	{
		"path": "move.keepout",
		"array": 1
	},
	{
		"path": "move.keepout[].active"
	},
	{
		"path": "move.keepout[].coords",
		"array": 1
	},
	{
		"path": "move.keepout[].coords[].max"
	},
	{
		"path": "move.keepout[].coords[].min"
	},
	{
		"path": "move.kinematics"
	},
	{
		"path": "move.kinematics.anchors",
		"array": 2
	},
	{
		"path": "move.kinematics.crosstalk",
		"array": 1
	},
	{
		"path": "move.kinematics.deltaRadius"
	},
	{
		"path": "move.kinematics.distalLength"
	},
	{
		"path": "move.kinematics.forwardMatrix",
		"array": 2
	},
	{
		"path": "move.kinematics.homedHeight"
	},
	{
		"path": "move.kinematics.inverseMatrix",
		"array": 2
	},
	{
		"path": "move.kinematics.minRadius"
	},
	{
		"path": "move.kinematics.name"
	},
	{
		"path": "move.kinematics.printRadius"
	},
	{
		"path": "move.kinematics.proximalLength"
	},
	{
		"path": "move.kinematics.psiLimits",
		"array": 1
	},
	{
		"path": "move.kinematics.radiusHomed"
	},
	{
		"path": "move.kinematics.radiusMax"
	},
	{
		"path": "move.kinematics.radiusMin"
	},
	{
		"path": "move.kinematics.segmentation"
	},
	{
		"path": "move.kinematics.segmentation.minSegLength"
	},
	{
		"path": "move.kinematics.segmentation.segmentsPerSec"
	},
	{
		"path": "move.kinematics.thetaLimits",
		"array": 1
	},
	{
		"path": "move.kinematics.tiltCorrection"
	},
	{
		"path": "move.kinematics.tiltCorrection.correctionFactor"
	},
	{
		"path": "move.kinematics.tiltCorrection.lastCorrections",
		"array": 1
	},
	{
		"path": "move.kinematics.tiltCorrection.maxCorrection"
	},
	{
		"path": "move.kinematics.tiltCorrection.screwPitch"
	},
	{
		"path": "move.kinematics.tiltCorrection.screwX",
		"array": 1
	},
	{
		"path": "move.kinematics.tiltCorrection.screwY",
		"array": 1
	},
	{
		"path": "move.kinematics.towers",
		"array": 1
	},
	{
		"path": "move.kinematics.towers[].angleCorrection"
	},
	{
		"path": "move.kinematics.towers[].diagonal"
	},
	{
		"path": "move.kinematics.towers[].endstopAdjustment"
	},
	{
		"path": "move.kinematics.towers[].xPos"
	},
	{
		"path": "move.kinematics.towers[].yPos"
	},
	{
		"path": "move.kinematics.ttAccMax"
	},
	{
		"path": "move.kinematics.ttSpeedMax"
	},
	{
		"path": "move.kinematics.xOffset"
	},
	{
		"path": "move.kinematics.xTilt"
	},
	{
		"path": "move.kinematics.yOffset"
	},
	{
		"path": "move.kinematics.yTilt"
	},
	{
		"path": "move.limitAxes"
	},
	{
		"path": "move.minSpeed",
		"since": "3.7.0-rc.1"
	},
	{
		"path": "move.motionSystems",
		"since": "3.7.0-beta.1",
		"array": 1
	},
	{
		"path": "move.motionSystems[].currentMove",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.acceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.deceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.distance",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.duration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.extrusionRate",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.laserPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.requestedSpeed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentMove.topSpeed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentObject",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].currentTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].nextTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].previousTool",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].printingAcceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints",
		"since": "3.7.0-beta.1",
		"array": 1
	},
	{
		"path": "move.motionSystems[].restorePoints[].coords",
		"since": "3.7.0-beta.1",
		"array": 1
	},
	{
		"path": "move.motionSystems[].restorePoints[].extruderPos",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].fanPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].feedRate",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].gCommandNumber",
		"since": "3.7.0-beta.2",
		"source": "RRF 3.7.0-beta.2 GCodes/RestorePoint.cpp:42 RestorePoint::objectModelTable - { \"gCommandNumber\" }; no such key in the tables at the 3.7.0-beta.1 tag",
		"note": "RRF serves restore point gCommandNumber from 3.7.0-beta.2 (GCodes/RestorePoint.cpp), not beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].ioBits",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].laserPwm",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].restorePoints[].toolNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation.angle",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].rotation.centre",
		"since": "3.7.0-beta.1",
		"array": 1
	},
	{
		"path": "move.motionSystems[].speedFactor",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].travelAcceleration",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].userPosition",
		"since": "3.7.0-beta.1",
		"array": 1
	},
	{
		"path": "move.motionSystems[].virtualEPos",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.motionSystems[].workplaceNumber",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "move.noMovesBeforeHoming"
	},
	{
		"path": "move.printingAcceleration",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use motionSystems[].printingAcceleration instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:189 - ObjectModelEntryFlags::obsolete (RRF d6d289afb, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "move.queue",
		"array": 1
	},
	{
		"path": "move.queue[].gracePeriod"
	},
	{
		"path": "move.queue[].length"
	},
	{
		"path": "move.rotation",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use motionSystems[].rotation instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:192 - ObjectModelEntryFlags::obsolete (RRF d6d289afb, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "move.rotation.angle"
	},
	{
		"path": "move.rotation.centre",
		"array": 1
	},
	{
		"path": "move.shaping"
	},
	{
		"path": "move.shaping.amplitudes",
		"array": 1
	},
	{
		"path": "move.shaping.damping"
	},
	{
		"path": "move.shaping.delays",
		"array": 1
	},
	{
		"path": "move.shaping.frequency"
	},
	{
		"path": "move.shaping.type"
	},
	{
		"path": "move.speedFactor"
	},
	{
		"path": "move.travelAcceleration",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use motionSystems[].travelAcceleration instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:196 - ObjectModelEntryFlags::obsolete (RRF d6d289afb, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "move.usingSCurve",
		"since": "3.7.0-alpha.2",
		"note": "RRF serves it from 3.7.0-alpha.2 (Movement/Move.cpp Move::objectModelTable, RRF bee83e350) on boards built with third-order motion control only; absent from RRF 3.6.3 although the Duet3D/ObjectModel v3.6.3 mirror declares it"
	},
	{
		"path": "move.virtualEPos",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use motionSystems[].virtualEPos instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:200 - ObjectModelEntryFlags::obsolete (RRF d6d289afb, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "move.workplaceNumber",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use motionSystems[].workplaceNumber instead",
			"source": "RRF 3.7.0-beta.1 Movement/Move.cpp:201 - ObjectModelEntryFlags::obsolete (RRF d6d289afb, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "network"
	},
	{
		"path": "network.corsSite"
	},
	{
		"path": "network.hostname"
	},
	{
		"path": "network.interfaces",
		"array": 1
	},
	{
		"path": "network.interfaces[].activeProtocols",
		"array": 1
	},
	{
		"path": "network.interfaces[].actualIP"
	},
	{
		"path": "network.interfaces[].configuredIP"
	},
	{
		"path": "network.interfaces[].dnsServer"
	},
	{
		"path": "network.interfaces[].firmwareVersion"
	},
	{
		"path": "network.interfaces[].gateway"
	},
	{
		"path": "network.interfaces[].mac"
	},
	{
		"path": "network.interfaces[].numReconnects",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "network.interfaces[].rssi"
	},
	{
		"path": "network.interfaces[].signal",
		"deprecated": {
			"since": "3.6.3",
			"message": "use rssi instead"
		}
	},
	{
		"path": "network.interfaces[].speed"
	},
	{
		"path": "network.interfaces[].ssid"
	},
	{
		"path": "network.interfaces[].state"
	},
	{
		"path": "network.interfaces[].subnet"
	},
	{
		"path": "network.interfaces[].type"
	},
	{
		"path": "network.interfaces[].wifiCountry"
	},
	{
		"path": "network.name"
	},
	{
		"path": "plugins",
		"array": 1
	},
	{
		"path": "plugins[].author"
	},
	{
		"path": "plugins[].data"
	},
	{
		"path": "plugins[].dsfFiles",
		"array": 1
	},
	{
		"path": "plugins[].dwcDependencies",
		"array": 1
	},
	{
		"path": "plugins[].dwcFiles",
		"array": 1
	},
	{
		"path": "plugins[].dwcVersion"
	},
	{
		"path": "plugins[].homepage"
	},
	{
		"path": "plugins[].id"
	},
	{
		"path": "plugins[].license"
	},
	{
		"path": "plugins[].name"
	},
	{
		"path": "plugins[].pid"
	},
	{
		"path": "plugins[].rrfVersion"
	},
	{
		"path": "plugins[].sbcAutoRestart"
	},
	{
		"path": "plugins[].sbcConfigFiles",
		"array": 1
	},
	{
		"path": "plugins[].sbcDsfVersion"
	},
	{
		"path": "plugins[].sbcExecutable"
	},
	{
		"path": "plugins[].sbcExecutableArguments"
	},
	{
		"path": "plugins[].sbcExtraExecutables",
		"array": 1
	},
	{
		"path": "plugins[].sbcNotifyStarted",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "plugins[].sbcOutputRedirected"
	},
	{
		"path": "plugins[].sbcPackageDependencies",
		"array": 1
	},
	{
		"path": "plugins[].sbcPermissions",
		"array": 1
	},
	{
		"path": "plugins[].sbcPluginDependencies",
		"array": 1
	},
	{
		"path": "plugins[].sbcPythonDependencies",
		"array": 1
	},
	{
		"path": "plugins[].sbcRequired"
	},
	{
		"path": "plugins[].sdFiles",
		"array": 1
	},
	{
		"path": "plugins[].started",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "plugins[].tags",
		"array": 1
	},
	{
		"path": "plugins[].version"
	},
	{
		"path": "sbc"
	},
	{
		"path": "sbc.appArmor"
	},
	{
		"path": "sbc.cpu"
	},
	{
		"path": "sbc.cpu.avgLoad"
	},
	{
		"path": "sbc.cpu.hardware"
	},
	{
		"path": "sbc.cpu.numCores"
	},
	{
		"path": "sbc.cpu.temperature"
	},
	{
		"path": "sbc.distribution"
	},
	{
		"path": "sbc.distributionBuildTime"
	},
	{
		"path": "sbc.dsf"
	},
	{
		"path": "sbc.dsf.buildDateTime"
	},
	{
		"path": "sbc.dsf.communicationMethod",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "sbc.dsf.httpEndpoints",
		"array": 1
	},
	{
		"path": "sbc.dsf.httpEndpoints[].endpointType"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].isUploadRequest"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].namespace"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].path"
	},
	{
		"path": "sbc.dsf.httpEndpoints[].unixSocket"
	},
	{
		"path": "sbc.dsf.is64Bit"
	},
	{
		"path": "sbc.dsf.pluginSupport"
	},
	{
		"path": "sbc.dsf.rootPluginSupport"
	},
	{
		"path": "sbc.dsf.userSessions",
		"array": 1
	},
	{
		"path": "sbc.dsf.userSessions[].accessLevel"
	},
	{
		"path": "sbc.dsf.userSessions[].id"
	},
	{
		"path": "sbc.dsf.userSessions[].origin"
	},
	{
		"path": "sbc.dsf.userSessions[].originId"
	},
	{
		"path": "sbc.dsf.userSessions[].sessionType"
	},
	{
		"path": "sbc.dsf.version"
	},
	{
		"path": "sbc.memory"
	},
	{
		"path": "sbc.memory.available"
	},
	{
		"path": "sbc.memory.total"
	},
	{
		"path": "sbc.model"
	},
	{
		"path": "sbc.serial"
	},
	{
		"path": "sbc.upgrade",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.upgrade.message",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.upgrade.progress",
		"since": "3.7.0-beta.3"
	},
	{
		"path": "sbc.uptime"
	},
	{
		"path": "sensors"
	},
	{
		"path": "sensors.accelerometers",
		"since": "3.7.0-rc.2",
		"array": 1,
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].orientation",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].points",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].port",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].resolution",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].runs",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.accelerometers[].samplingRate",
		"since": "3.7.0-rc.2",
		"source": "RRF 3.7.0-rc.2 Accelerometers/Accelerometers.cpp:45-57 Accelerometer::objectModelTable (orientation, points, port, resolution, runs, samplingRate), Endstops/EndstopsManager.cpp:87-92,103,112 (sensors.accelerometers, array table 5) - RRF commit 0ee0de8800 'Moved accelerometers from boards[] to sensors.accelerometers[]', Version.h 3.7.0-rc.1+3"
	},
	{
		"path": "sensors.analog",
		"array": 1
	},
	{
		"path": "sensors.analog[].beta"
	},
	{
		"path": "sensors.analog[].c"
	},
	{
		"path": "sensors.analog[].highReading"
	},
	{
		"path": "sensors.analog[].lastReading"
	},
	{
		"path": "sensors.analog[].lowReading"
	},
	{
		"path": "sensors.analog[].name"
	},
	{
		"path": "sensors.analog[].offsetAdj"
	},
	{
		"path": "sensors.analog[].port"
	},
	{
		"path": "sensors.analog[].r25"
	},
	{
		"path": "sensors.analog[].rRef"
	},
	{
		"path": "sensors.analog[].slopeAdj"
	},
	{
		"path": "sensors.analog[].state"
	},
	{
		"path": "sensors.analog[].type"
	},
	{
		"path": "sensors.endstops",
		"array": 1
	},
	{
		"path": "sensors.endstops[].highEnd"
	},
	{
		"path": "sensors.endstops[].probe"
	},
	{
		"path": "sensors.endstops[].triggered"
	},
	{
		"path": "sensors.endstops[].type"
	},
	{
		"path": "sensors.filamentMonitors",
		"array": 1
	},
	{
		"path": "sensors.filamentMonitors[].agc",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 FilamentMonitors/RotatingMagnetFilamentMonitor.cpp:35 RotatingMagnetFilamentMonitor::objectModelTable - { \"agc\", OBJECT_MODEL_FUNC_IF(self->haveAgc, ...) } (RRF commit d30c34b0a \"Added AGC data for filament monitors (#756)\"); at the 3.7.0-beta.2 tag the key sat inside #ifdef DUET3_ATE, so no regular build served it"
	},
	{
		"path": "sensors.filamentMonitors[].avgPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.mmPerPulse"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.mmPerRev"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.percentMax"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.percentMin"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.sensitivity"
	},
	{
		"path": "sensors.filamentMonitors[].calibrated.totalDistance"
	},
	{
		"path": "sensors.filamentMonitors[].configured"
	},
	{
		"path": "sensors.filamentMonitors[].configured.allMoves"
	},
	{
		"path": "sensors.filamentMonitors[].configured.calibrationFactor"
	},
	{
		"path": "sensors.filamentMonitors[].configured.mmPerPulse"
	},
	{
		"path": "sensors.filamentMonitors[].configured.mmPerRev"
	},
	{
		"path": "sensors.filamentMonitors[].configured.percentMax"
	},
	{
		"path": "sensors.filamentMonitors[].configured.percentMin"
	},
	{
		"path": "sensors.filamentMonitors[].configured.sampleDistance"
	},
	{
		"path": "sensors.filamentMonitors[].enableMode"
	},
	{
		"path": "sensors.filamentMonitors[].enabled",
		"deprecated": {
			"since": "3.6.3",
			"message": "use enableMode instead"
		}
	},
	{
		"path": "sensors.filamentMonitors[].filamentPresent",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 FilamentMonitors/FilamentMonitor.cpp:54 FilamentMonitor::objectModelTable - { \"filamentPresent\" }; absent from the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.filamentMonitors[].lastPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].maxPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].minPercentage"
	},
	{
		"path": "sensors.filamentMonitors[].position"
	},
	{
		"path": "sensors.filamentMonitors[].status"
	},
	{
		"path": "sensors.filamentMonitors[].totalExtrusion"
	},
	{
		"path": "sensors.filamentMonitors[].type"
	},
	{
		"path": "sensors.gpIn",
		"array": 1
	},
	{
		"path": "sensors.gpIn[].value"
	},
	{
		"path": "sensors.probes",
		"array": 1
	},
	{
		"path": "sensors.probes[].calibA",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "sensors.probes[].calibB",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "sensors.probes[].calibrationTemperature"
	},
	{
		"path": "sensors.probes[].deployedByUser"
	},
	{
		"path": "sensors.probes[].disablesHeaters"
	},
	{
		"path": "sensors.probes[].diveHeight",
		"deprecated": {
			"since": "3.6.3",
			"message": "use diveHeights[0] instead"
		}
	},
	{
		"path": "sensors.probes[].diveHeights",
		"array": 1
	},
	{
		"path": "sensors.probes[].isCalibrated"
	},
	{
		"path": "sensors.probes[].lastStopHeight"
	},
	{
		"path": "sensors.probes[].loadCell",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 Endstops/ZProbe.cpp:99,123-125 ZProbe::objectModelTable (loadCell; force, gramsPerCount, preload, preloadWindow); no such keys in the tables at the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.probes[].loadCell.force",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 Endstops/ZProbe.cpp:99,123-125 ZProbe::objectModelTable (loadCell; force, gramsPerCount, preload, preloadWindow); no such keys in the tables at the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.probes[].loadCell.gramsPerCount",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 Endstops/ZProbe.cpp:99,123-125 ZProbe::objectModelTable (loadCell; force, gramsPerCount, preload, preloadWindow); no such keys in the tables at the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.probes[].loadCell.preload",
		"since": "3.7.0-beta.3",
		"source": "RRF 3.7.0-beta.3 Endstops/ZProbe.cpp:99,123-125 ZProbe::objectModelTable (loadCell; force, gramsPerCount, preload, preloadWindow); no such keys in the tables at the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.probes[].loadCell.preloadWindow",
		"since": "3.7.0-beta.3",
		"array": 1,
		"source": "RRF 3.7.0-beta.3 Endstops/ZProbe.cpp:99,123-125 ZProbe::objectModelTable (loadCell; force, gramsPerCount, preload, preloadWindow); no such keys in the tables at the 3.7.0-beta.2 tag"
	},
	{
		"path": "sensors.probes[].maxProbeCount"
	},
	{
		"path": "sensors.probes[].measuredHeight"
	},
	{
		"path": "sensors.probes[].offsets",
		"array": 1
	},
	{
		"path": "sensors.probes[].recoveryTime"
	},
	{
		"path": "sensors.probes[].scanCoefficients",
		"array": 1
	},
	{
		"path": "sensors.probes[].speeds",
		"array": 1
	},
	{
		"path": "sensors.probes[].temperatureCoefficients",
		"array": 1
	},
	{
		"path": "sensors.probes[].threshold"
	},
	{
		"path": "sensors.probes[].tolerance"
	},
	{
		"path": "sensors.probes[].touchMode"
	},
	{
		"path": "sensors.probes[].touchMode.active"
	},
	{
		"path": "sensors.probes[].touchMode.sensitivity",
		"until": "3.7.0-alpha.2"
	},
	{
		"path": "sensors.probes[].touchMode.speed",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "sensors.probes[].touchMode.threshold"
	},
	{
		"path": "sensors.probes[].touchMode.triggerHeight"
	},
	{
		"path": "sensors.probes[].travelSpeed"
	},
	{
		"path": "sensors.probes[].triggerHeight"
	},
	{
		"path": "sensors.probes[].type"
	},
	{
		"path": "sensors.probes[].value",
		"array": 1
	},
	{
		"path": "seqs",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.boards",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.directories",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.fans",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.global",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.heat",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.inputs",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.job",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.ledStrips",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.move",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.network",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.reply",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.sensors",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.spindles",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.state",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.tools",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "seqs.volChanges",
		"array": 1,
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275); array table 8, Platform/RepRap.cpp:230-240"
	},
	{
		"path": "seqs.volumes",
		"source": "RRF 3.7.0-rc.2 (RepRap.cpp is byte-identical to 3.7.0-rc.1) and 3.6.3 Platform/RepRap.cpp table 5 (`// 5. seqs`, root key `seqs` at :276/:275)"
	},
	{
		"path": "spindles",
		"array": 1
	},
	{
		"path": "spindles[].active"
	},
	{
		"path": "spindles[].canReverse"
	},
	{
		"path": "spindles[].current"
	},
	{
		"path": "spindles[].frequency"
	},
	{
		"path": "spindles[].idlePwm"
	},
	{
		"path": "spindles[].max"
	},
	{
		"path": "spindles[].maxPwm"
	},
	{
		"path": "spindles[].min"
	},
	{
		"path": "spindles[].minPwm"
	},
	{
		"path": "spindles[].state"
	},
	{
		"path": "spindles[].type"
	},
	{
		"path": "state"
	},
	{
		"path": "state.atxPower"
	},
	{
		"path": "state.atxPowerPort"
	},
	{
		"path": "state.beep"
	},
	{
		"path": "state.beep.duration"
	},
	{
		"path": "state.beep.frequency"
	},
	{
		"path": "state.currentTool"
	},
	{
		"path": "state.deferredPowerDown"
	},
	{
		"path": "state.displayMessage"
	},
	{
		"path": "state.gpOut",
		"array": 1
	},
	{
		"path": "state.gpOut[].freq"
	},
	{
		"path": "state.gpOut[].pwm"
	},
	{
		"path": "state.laserPwm"
	},
	{
		"path": "state.logFile"
	},
	{
		"path": "state.logLevel"
	},
	{
		"path": "state.machineMode"
	},
	{
		"path": "state.macroRestarted"
	},
	{
		"path": "state.messageBox"
	},
	{
		"path": "state.messageBox.axisControls"
	},
	{
		"path": "state.messageBox.cancelButton"
	},
	{
		"path": "state.messageBox.choices",
		"array": 1
	},
	{
		"path": "state.messageBox.default"
	},
	{
		"path": "state.messageBox.max"
	},
	{
		"path": "state.messageBox.message"
	},
	{
		"path": "state.messageBox.min"
	},
	{
		"path": "state.messageBox.mode"
	},
	{
		"path": "state.messageBox.seq"
	},
	{
		"path": "state.messageBox.timeout"
	},
	{
		"path": "state.messageBox.title"
	},
	{
		"path": "state.msUpTime"
	},
	{
		"path": "state.nextTool",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use move.motionSystems[].nextTool instead",
			"source": "RRF 3.7.0-beta.1 Platform/RepRap.cpp:359 - ObjectModelEntryFlags::obsolete (RRF c4b2b3293, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "state.pluginsStarted"
	},
	{
		"path": "state.powerFailScript"
	},
	{
		"path": "state.previousTool",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use move.motionSystems[].previousTool instead",
			"source": "RRF 3.7.0-beta.1 Platform/RepRap.cpp:363 - ObjectModelEntryFlags::obsolete (RRF c4b2b3293, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		}
	},
	{
		"path": "state.restorePoints",
		"deprecated": {
			"since": "3.7.0-beta.1",
			"message": "use move.motionSystems[].restorePoints instead",
			"source": "RRF 3.7.0-beta.1 Platform/RepRap.cpp:364 - ObjectModelEntryFlags::obsolete (RRF c4b2b3293, first in the 3.7.0-alpha.3 build; 3.6.3 and 3.7.0-alpha.2 do not flag it); reading it in an expression prints \"obsolete object model field ... queried\" (GCodes/GCodeBuffer/ExpressionParser.cpp:171-176) and M409 omits it unless asked"
		},
		"array": 1
	},
	{
		"path": "state.restorePoints[].coords",
		"array": 1
	},
	{
		"path": "state.restorePoints[].extruderPos"
	},
	{
		"path": "state.restorePoints[].fanPwm"
	},
	{
		"path": "state.restorePoints[].feedRate"
	},
	{
		"path": "state.restorePoints[].gCommandNumber",
		"since": "3.7.0-beta.2",
		"source": "RRF 3.7.0-beta.2 GCodes/RestorePoint.cpp:42 RestorePoint::objectModelTable - { \"gCommandNumber\" }; no such key in the tables at the 3.7.0-beta.1 tag",
		"note": "RRF serves restore point gCommandNumber from 3.7.0-beta.2 (GCodes/RestorePoint.cpp), not beta.1"
	},
	{
		"path": "state.restorePoints[].ioBits"
	},
	{
		"path": "state.restorePoints[].laserPwm"
	},
	{
		"path": "state.restorePoints[].toolNumber"
	},
	{
		"path": "state.startupError"
	},
	{
		"path": "state.startupError.file"
	},
	{
		"path": "state.startupError.line"
	},
	{
		"path": "state.startupError.message"
	},
	{
		"path": "state.status"
	},
	{
		"path": "state.thisActive",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "state.thisInput"
	},
	{
		"path": "state.time"
	},
	{
		"path": "state.upTime"
	},
	{
		"path": "tools",
		"array": 1
	},
	{
		"path": "tools[].active",
		"array": 1
	},
	{
		"path": "tools[].axes",
		"array": 2
	},
	{
		"path": "tools[].extruders",
		"array": 1
	},
	{
		"path": "tools[].fans",
		"array": 1
	},
	{
		"path": "tools[].feedForward",
		"deprecated": {
			"since": "3.6.3",
			"message": "use feedForwardPwm instead"
		},
		"array": 1
	},
	{
		"path": "tools[].feedForwardAdvance"
	},
	{
		"path": "tools[].feedForwardPwm",
		"array": 1
	},
	{
		"path": "tools[].feedForwardTemp",
		"array": 1
	},
	{
		"path": "tools[].filamentExtruder"
	},
	{
		"path": "tools[].heaters",
		"array": 1
	},
	{
		"path": "tools[].isRetracted"
	},
	{
		"path": "tools[].mix",
		"array": 1
	},
	{
		"path": "tools[].name"
	},
	{
		"path": "tools[].number"
	},
	{
		"path": "tools[].offsets",
		"array": 1
	},
	{
		"path": "tools[].offsetsProbed"
	},
	{
		"path": "tools[].retraction"
	},
	{
		"path": "tools[].retraction.extraRestart"
	},
	{
		"path": "tools[].retraction.length"
	},
	{
		"path": "tools[].retraction.speed"
	},
	{
		"path": "tools[].retraction.unretractSpeed"
	},
	{
		"path": "tools[].retraction.zHop"
	},
	{
		"path": "tools[].spindle"
	},
	{
		"path": "tools[].spindleRpm"
	},
	{
		"path": "tools[].standby",
		"array": 1
	},
	{
		"path": "tools[].state"
	},
	{
		"path": "volumes",
		"array": 1
	},
	{
		"path": "volumes[].capacity"
	},
	{
		"path": "volumes[].freeSpace"
	},
	{
		"path": "volumes[].mounted"
	},
	{
		"path": "volumes[].name"
	},
	{
		"path": "volumes[].openFiles"
	},
	{
		"path": "volumes[].partitionSize",
		"since": "3.7.0-beta.1"
	},
	{
		"path": "volumes[].path"
	},
	{
		"path": "volumes[].speed"
	}
];
const PATHS = OBJECT_MODEL_PATHS;

const BY_PATH: ReadonlyMap<string, ObjectModelPathEntry> = new Map(PATHS.map((e) => [e.path, e]));
const TRACKED_ORDER: ReadonlyArray<string> = ["3.6.3","3.7.0-alpha.2","3.7.0-beta.1","3.7.0-beta.2","3.7.0-beta.3","3.7.0-rc.1","3.7.0-rc.2"];

/** The entry `path` refers to. A path that is itself a listed entry is that entry; one that is a listed
 *  entry plus trailing `[]` groups - an element of an array (`heat.heaters[]`, `sensors.probes[].offsets[]`,
 *  `heat.bedHeaterMapping[][]`) - refers to the array's own entry, as long as the array can be indexed
 *  that many times. Neither documentation.json nor RRF's tables list `X[]` separately from `X`. */
function entryFor(path: string): ObjectModelPathEntry | undefined {
	const direct = BY_PATH.get(path);
	if (direct !== undefined) return direct;
	let base = path;
	let depth = 0;
	while (base.endsWith("[]")) {
		base = base.slice(0, -2);
		depth++;
	}
	if (depth === 0) return undefined;
	const owner = BY_PATH.get(base);
	return owner !== undefined && (owner.array ?? 0) >= depth ? owner : undefined;
}

function trackedIndex(version: string): number {
	const i = TRACKED_ORDER.indexOf(version);
	if (i === -1) {
		const known = OBJECT_MODEL_VERSIONS.find((v) => v.version === version);
		throw new Error(
			known === undefined
				? `"${version}" is not one of OBJECT_MODEL_VERSIONS`
				: `"${version}" has no object-model data (OBJECT_MODEL_VERSIONS reports hasData: false)`,
		);
	}
	return i;
}

export interface ObjectModelPathStatus {
	known: boolean;
	deprecated?: string;
	since?: string;
	until?: string;
}

/** Whether `path` (already normalised - `[]` for every array/dictionary index, as task 07's
 *  expression-path handling already produces; a trailing `[]` on an indexable path is accepted, see
 *  `entryFor`) is part of the object model at `rrfVersion`, and
 *  whether/since-when it's deprecated. Throws if `rrfVersion` isn't one of OBJECT_MODEL_VERSIONS or
 *  has no tracked data (see ObjectModelVersionInfo.hasData). */
export function objectModelPath(path: string, rrfVersion: string): ObjectModelPathStatus {
	const versionIndex = trackedIndex(rrfVersion);
	const entry = entryFor(path);
	if (entry === undefined) return { known: false };
	const sinceIndex = entry.since === undefined ? 0 : trackedIndex(entry.since);
	const untilIndex = entry.until === undefined ? TRACKED_ORDER.length - 1 : trackedIndex(entry.until);
	const known = versionIndex >= sinceIndex && versionIndex <= untilIndex;
	if (!known) return { known: false };
	const result: ObjectModelPathStatus = { known: true };
	if (entry.since !== undefined) result.since = entry.since;
	if (entry.until !== undefined) result.until = entry.until;
	if (entry.deprecated !== undefined && trackedIndex(entry.deprecated.since) <= versionIndex) {
		result.deprecated = entry.deprecated.message;
	}
	return result;
}

export interface ObjectModelChange {
	path: string;
	change: "added" | "removed" | "deprecated";
	version: string;
}

/** Every object-model path change between two tracked versions, in the direction actually given -
 *  a downgrade (`toVersion` older than `fromVersion`) reports each addition going forward as a
 *  "removed" and each removal going forward as an "added", so the result always describes what
 *  changes moving from `fromVersion` to `toVersion`, whichever way that runs. */
export function objectModelChanges(fromVersion: string, toVersion: string): ReadonlyArray<ObjectModelChange> {
	const fromIndex = trackedIndex(fromVersion);
	const toIndex = trackedIndex(toVersion);
	const forward = toIndex >= fromIndex;
	const [lo, hi] = forward ? [fromIndex, toIndex] : [toIndex, fromIndex];
	const changes: Array<ObjectModelChange> = [];
	for (const entry of PATHS) {
		const sinceIndex = entry.since === undefined ? 0 : trackedIndex(entry.since);
		const untilIndex = entry.until === undefined ? TRACKED_ORDER.length - 1 : trackedIndex(entry.until);
		const presentAtLo = sinceIndex <= lo && lo <= untilIndex;
		const presentAtHi = sinceIndex <= hi && hi <= untilIndex;
		// The reported "version" is always the actual RRF version the underlying transition happened
		// at: entry.since for an addition, and for a removal the first tracked version AFTER entry.until (which is
		// the LAST version the path is present in - reporting it would date the removal to a version the path
		// still exists in, outside the (from, to] window of the very query that found it) -
		// direction only flips which LABEL ("added" vs "removed") that same transition gets, not
		// where it's pinned. Pinning it to a range endpoint instead (an earlier version of this
		// function did exactly that) reports the wrong version for every downgrade comparison whose
		// range doesn't start/end exactly on the transition itself.
		if (!presentAtLo && presentAtHi) {
			changes.push({ path: entry.path, change: forward ? "added" : "removed", version: entry.since ?? TRACKED_ORDER[lo] });
		} else if (presentAtLo && !presentAtHi) {
			changes.push({ path: entry.path, change: forward ? "removed" : "added", version: TRACKED_ORDER[untilIndex + 1] ?? TRACKED_ORDER[hi] });
		}
		if (entry.deprecated !== undefined) {
			const depIndex = trackedIndex(entry.deprecated.since);
			if (depIndex > lo && depIndex <= hi) {
				changes.push({ path: entry.path, change: "deprecated", version: entry.deprecated.since });
			}
		}
	}
	return changes.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
