/**
 * RRF release <-> @duet3d/objectmodel version mapping (task 11, docs/tasks/11-object-model-schema.md).
 * GENERATED by scripts/build-om-schema.mjs - do not hand-edit.
 */

export interface ObjectModelVersionInfo {
	/** RRF/npm version string, e.g. "3.6.3". Exact match between an RRF git tag and an
	 *  @duet3d/objectmodel npm version - see the generator script's own VERSIONS_IN_WINDOW. */
	version: string;
	/** False when no object-model path data exists for this version (none at present: "3.7.0-alpha.2"'s is derived
	 *  from its neighbours and RRF's own tables, see the generator's RRF_TABLE_DERIVED) - objectModelPath and
	 *  objectModelChanges never accept such a version as an endpoint. */
	hasData: boolean;
}

export const OBJECT_MODEL_VERSIONS: ReadonlyArray<ObjectModelVersionInfo> = [
	{
		"version": "3.6.3",
		"hasData": true
	},
	{
		"version": "3.7.0-alpha.2",
		"hasData": true
	},
	{
		"version": "3.7.0-beta.1",
		"hasData": true
	},
	{
		"version": "3.7.0-beta.2",
		"hasData": true
	},
	{
		"version": "3.7.0-beta.3",
		"hasData": true
	},
	{
		"version": "3.7.0-rc.1",
		"hasData": true
	},
	{
		"version": "3.7.0-rc.2",
		"hasData": true
	}
];

/** The newest RRF release this schema has object-model data for. */
export const OBJECT_MODEL_BASELINE = "3.7.0-rc.2";
