/**
 * RRF release <-> @duet3d/objectmodel version mapping (task 11, docs/tasks/11-object-model-schema.md).
 * GENERATED by scripts/build-om-schema.mjs - do not hand-edit.
 */

export interface ObjectModelVersionInfo {
	/** RRF/npm version string, e.g. "3.6.3". Exact match between an RRF git tag and an
	 *  @duet3d/objectmodel npm version - see the generator script's own VERSIONS_IN_WINDOW. */
	version: string;
	/** False when neither @duet3d/objectmodel's npm package nor Duet3D/ObjectModel's git tags carry
	 *  usable object-model source for this version (currently just "3.7.0-alpha.2") - objectModelPath
	 *  and objectModelChanges never accept this version as an endpoint. */
	hasData: boolean;
}

export const OBJECT_MODEL_VERSIONS: ReadonlyArray<ObjectModelVersionInfo> = [
	{
		"version": "3.6.3",
		"hasData": true
	},
	{
		"version": "3.7.0-alpha.2",
		"hasData": false
	},
	{
		"version": "3.7.0-beta.1",
		"hasData": true
	},
	{
		"version": "3.7.0-beta.2",
		"hasData": true
	},
	{
		"version": "3.7.0-beta.3",
		"hasData": true
	},
	{
		"version": "3.7.0-rc.1",
		"hasData": true
	}
];

/** The newest RRF release this schema has object-model data for. */
export const OBJECT_MODEL_BASELINE = "3.7.0-rc.1";
