#!/usr/bin/env node
/**
 * Generates `docs/api.md` (task 16's own "API review": list every export, make sure every subpath is
 * documented) - one section per `package.json` `exports` subpath, each export name and whether it's
 * a runtime value (function/const/class - found by actually importing the built `.js` and listing
 * `Object.keys`) or a type-only export (interface/type alias - found by scanning the matching `.d.ts`
 * for `export (interface|type) Name`, since a type has no runtime presence to introspect). Run after
 * `npm run build`, since it reads `dist/`, not `src/` - matches `scripts/build-diagnostics-doc.mjs`'s
 * own convention.
 *
 *   npm run build && node scripts/build-api-doc.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DIST = join(ROOT, "dist");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));

/** Every concrete `[subpath, distJsRelativePath]` pair, wildcard `exports` entries expanded against
 *  what's actually in `dist/`. */
function concreteSubpaths() {
	const out = [];
	for (const key of Object.keys(pkg.exports)) {
		if (key === "./package.json") continue;
		if (key === ".") { out.push([".", "index.js"]); continue; }
		const sub = key.slice(2); // drop "./"
		if (sub.endsWith("/*")) {
			const dir = sub.slice(0, -2);
			for (const name of readdirSync(join(DIST, dir)).sort()) {
				if (name.endsWith(".js")) out.push([`${dir}/${name.slice(0, -3)}`, `${dir}/${name}`]);
			}
		} else {
			out.push([sub, `${sub}.js`]);
		}
	}
	return out;
}

/** Type-only export names (`interface`/`type`) from a `.d.ts` file - a plain top-of-line regex scan,
 *  good enough for a generated listing (not a re-implementation of the TS compiler); multi-line
 *  declarations are still caught since the `export` keyword itself is always on its own line's start
 *  in this codebase's own generated/hand-written `.ts` sources. */
function typeOnlyExports(dtsPath) {
	const text = readFileSync(dtsPath, "utf-8");
	const names = [];
	const re = /^export (?:declare )?(interface|type) ([A-Za-z0-9_]+)/gm;
	let m;
	while ((m = re.exec(text)) !== null) names.push({ name: m[2], kind: m[1] });
	return names;
}

async function runtimeExports(jsPath) {
	const mod = await import(new URL(`file://${jsPath.replace(/\\/g, "/")}`).href);
	return Object.keys(mod).sort().map((name) => ({ name, kind: typeof mod[name] === "function" ? "function" : "const" }));
}

async function main() {
	let out = "# API surface\n\n";
	out += "Generated by `scripts/build-api-doc.mjs` - every `package.json` `exports` subpath and what it ";
	out += "exports, split into runtime values (functions/consts/classes) and type-only exports ";
	out += "(interfaces/type aliases, which have no runtime presence). See the README for usage examples ";
	out += "and which subpaths are deliberately NOT re-exported from the root (`/edit`, `/dictionary/*`) ";
	out += "and why.\n\n";

	for (const [subpath, jsRel] of concreteSubpaths()) {
		const jsPath = join(DIST, jsRel);
		const dtsPath = jsPath.replace(/\.js$/, ".d.ts");
		const runtime = await runtimeExports(jsPath);
		const types = typeOnlyExports(dtsPath).filter((t) => !runtime.some((r) => r.name === t.name));
		out += `## \`dwc-gcode-core${subpath === "." ? "" : `/${subpath}`}\`\n\n`;
		if (runtime.length > 0) {
			out += "Runtime: " + runtime.map((r) => `\`${r.name}\` (${r.kind})`).join(", ") + "\n\n";
		}
		if (types.length > 0) {
			out += "Types only: " + types.map((t) => `\`${t.name}\` (${t.kind})`).join(", ") + "\n\n";
		}
		if (runtime.length === 0 && types.length === 0) out += "*(no exports found - check the build)*\n\n";
	}

	writeFileSync(join(ROOT, "docs", "api.md"), out);
	console.log(`Wrote ${join(ROOT, "docs", "api.md")}`);
}

await main();
