/**
 * Official Duet mainboard pin tables - GENERATED by `scripts/build-pin-tables-duet.mjs` from each
 * board's own compiled `PinTable[]` in `RepRapFirmware/src/Config/Pins_*.h`. Do not hand-edit; edit
 * the generator (or re-run it against updated RRF source) instead. See
 * `docs/tasks/17-pin-names-and-validation.md` (Part B). `Pins_FMDC.h` is deliberately NOT included -
 * see the generator script's own doc comment (real conditional compilation it doesn't resolve).
 */

import type { BoardPinTable } from "./schema.js";

export const DUET_BOARD_PIN_TABLES: ReadonlyArray<BoardPinTable> = Object.freeze(
[
	{
		"boardId": "duet3-indx",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "pcfan.tach",
				"aliases": [
					"pcfan.tach"
				]
			},
			{
				"canonicalName": "pcfan",
				"aliases": [
					"pcfan"
				]
			},
			{
				"canonicalName": "ate.vin",
				"aliases": [
					"ate.vin"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "io0.in",
				"aliases": [
					"io0.in"
				]
			},
			{
				"canonicalName": "ate.envtemp",
				"aliases": [
					"ate.envtemp"
				]
			},
			{
				"canonicalName": "hsfan.tach",
				"aliases": [
					"hsfan.tach"
				]
			},
			{
				"canonicalName": "hsfan",
				"aliases": [
					"hsfan"
				]
			},
			{
				"canonicalName": "ate.heaterv",
				"aliases": [
					"ate.heaterv"
				]
			},
			{
				"canonicalName": "boardtemp",
				"aliases": [
					"boardtemp"
				]
			},
			{
				"canonicalName": "coiltemp",
				"aliases": [
					"coiltemp"
				]
			},
			{
				"canonicalName": "pb30",
				"aliases": [
					"pb30"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_Duet3_INDX.h PinTable[]"
		]
	},
	{
		"boardId": "duet3-mb6hc",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "io6.out",
				"aliases": [
					"io6.out"
				]
			},
			{
				"canonicalName": "out6.tach",
				"aliases": [
					"out6.tach"
				]
			},
			{
				"canonicalName": "io3.out",
				"aliases": [
					"io3.out"
				]
			},
			{
				"canonicalName": "spi.cs0",
				"aliases": [
					"spi.cs0",
					"serial3.rx"
				]
			},
			{
				"canonicalName": "spi.cs1",
				"aliases": [
					"spi.cs1",
					"serial3.tx"
				]
			},
			{
				"canonicalName": "out0",
				"aliases": [
					"out0"
				]
			},
			{
				"canonicalName": "out6",
				"aliases": [
					"out6"
				]
			},
			{
				"canonicalName": "pson",
				"aliases": [
					"pson"
				]
			},
			{
				"canonicalName": "out3",
				"aliases": [
					"out3"
				]
			},
			{
				"canonicalName": "out9",
				"aliases": [
					"out9",
					"laser",
					"vfd"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "led.clk",
				"aliases": [
					"led.clk"
				]
			},
			{
				"canonicalName": "out4",
				"aliases": [
					"out4"
				]
			},
			{
				"canonicalName": "out2",
				"aliases": [
					"out2"
				]
			},
			{
				"canonicalName": "io7.in",
				"aliases": [
					"io7.in"
				]
			},
			{
				"canonicalName": "io6.in",
				"aliases": [
					"io6.in"
				]
			},
			{
				"canonicalName": "io5.in",
				"aliases": [
					"io5.in"
				]
			},
			{
				"canonicalName": "out1",
				"aliases": [
					"out1"
				]
			},
			{
				"canonicalName": "out5",
				"aliases": [
					"out5"
				]
			},
			{
				"canonicalName": "ate.usbpwren",
				"aliases": [
					"ate.usbpwren"
				]
			},
			{
				"canonicalName": "out4.tach",
				"aliases": [
					"out4.tach"
				]
			},
			{
				"canonicalName": "out8",
				"aliases": [
					"out8"
				]
			},
			{
				"canonicalName": "rs485.tx",
				"aliases": [
					"rs485.tx"
				]
			},
			{
				"canonicalName": "out7",
				"aliases": [
					"out7"
				]
			},
			{
				"canonicalName": "temp0",
				"aliases": [
					"temp0"
				]
			},
			{
				"canonicalName": "spi.cs3",
				"aliases": [
					"spi.cs3"
				]
			},
			{
				"canonicalName": "io7.out",
				"aliases": [
					"io7.out"
				]
			},
			{
				"canonicalName": "temp1",
				"aliases": [
					"temp1"
				]
			},
			{
				"canonicalName": "temp2",
				"aliases": [
					"temp2"
				]
			},
			{
				"canonicalName": "temp3",
				"aliases": [
					"temp3"
				]
			},
			{
				"canonicalName": "io1.in",
				"aliases": [
					"io1.in",
					"serial1.rx"
				]
			},
			{
				"canonicalName": "io1.out",
				"aliases": [
					"io1.out",
					"serial1.tx"
				]
			},
			{
				"canonicalName": "spi.cs2",
				"aliases": [
					"spi.cs2"
				]
			},
			{
				"canonicalName": "io5.out",
				"aliases": [
					"io5.out"
				]
			},
			{
				"canonicalName": "out5.tach",
				"aliases": [
					"out5.tach"
				]
			},
			{
				"canonicalName": "io0.in",
				"aliases": [
					"io0.in",
					"serial0.rx"
				]
			},
			{
				"canonicalName": "io0.out",
				"aliases": [
					"io0.out",
					"serial0.tx"
				]
			},
			{
				"canonicalName": "io2.out",
				"aliases": [
					"io2.out",
					"i2c0.dat"
				]
			},
			{
				"canonicalName": "io2.in",
				"aliases": [
					"io2.in",
					"i2c0.clk"
				]
			},
			{
				"canonicalName": "io4.in",
				"aliases": [
					"io4.in"
				]
			},
			{
				"canonicalName": "io4.out",
				"aliases": [
					"io4.out"
				]
			},
			{
				"canonicalName": "io8.out",
				"aliases": [
					"io8.out"
				]
			},
			{
				"canonicalName": "io8.in",
				"aliases": [
					"io8.in"
				]
			},
			{
				"canonicalName": "io3.in",
				"aliases": [
					"io3.in"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_Duet3_MB6HC.h PinTable[]"
		]
	},
	{
		"boardId": "duet3-mb6xd",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "io6.out",
				"aliases": [
					"io6.out",
					"io6.out.iso"
				]
			},
			{
				"canonicalName": "out5.tach",
				"aliases": [
					"out5.tach"
				]
			},
			{
				"canonicalName": "io3.out",
				"aliases": [
					"io3.out"
				]
			},
			{
				"canonicalName": "spi.cs1",
				"aliases": [
					"spi.cs1",
					"serial3.rx"
				]
			},
			{
				"canonicalName": "spi.cs2",
				"aliases": [
					"spi.cs2",
					"serial3.tx"
				]
			},
			{
				"canonicalName": "laser",
				"aliases": [
					"laser",
					"vfd"
				]
			},
			{
				"canonicalName": "out5",
				"aliases": [
					"out5"
				]
			},
			{
				"canonicalName": "pson",
				"aliases": [
					"pson"
				]
			},
			{
				"canonicalName": "out2",
				"aliases": [
					"out2"
				]
			},
			{
				"canonicalName": "out8",
				"aliases": [
					"out8"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "led.clk",
				"aliases": [
					"led.clk"
				]
			},
			{
				"canonicalName": "out3",
				"aliases": [
					"out3"
				]
			},
			{
				"canonicalName": "out1",
				"aliases": [
					"out1"
				]
			},
			{
				"canonicalName": "io7.in",
				"aliases": [
					"io7.in",
					"io7.in.iso"
				]
			},
			{
				"canonicalName": "io6.in",
				"aliases": [
					"io6.in",
					"io6.in.iso"
				]
			},
			{
				"canonicalName": "io5.in",
				"aliases": [
					"io5.in",
					"io5.in.iso"
				]
			},
			{
				"canonicalName": "out0",
				"aliases": [
					"out0"
				]
			},
			{
				"canonicalName": "temp2",
				"aliases": [
					"temp2"
				]
			},
			{
				"canonicalName": "driver3.err",
				"aliases": [
					"driver3.err"
				]
			},
			{
				"canonicalName": "out4",
				"aliases": [
					"out4"
				]
			},
			{
				"canonicalName": "ate.usbpwren",
				"aliases": [
					"ate.usbpwren"
				]
			},
			{
				"canonicalName": "out3.tach",
				"aliases": [
					"out3.tach"
				]
			},
			{
				"canonicalName": "out7",
				"aliases": [
					"out7"
				]
			},
			{
				"canonicalName": "driver5.err",
				"aliases": [
					"driver5.err"
				]
			},
			{
				"canonicalName": "out6",
				"aliases": [
					"out6"
				]
			},
			{
				"canonicalName": "temp0",
				"aliases": [
					"temp0"
				]
			},
			{
				"canonicalName": "driver1.err",
				"aliases": [
					"driver1.err"
				]
			},
			{
				"canonicalName": "spi.cs4",
				"aliases": [
					"spi.cs4"
				]
			},
			{
				"canonicalName": "io7.out",
				"aliases": [
					"io7.out",
					"io7.out.iso"
				]
			},
			{
				"canonicalName": "temp1",
				"aliases": [
					"temp1"
				]
			},
			{
				"canonicalName": "temp3",
				"aliases": [
					"temp3"
				]
			},
			{
				"canonicalName": "driver2.err",
				"aliases": [
					"driver2.err"
				]
			},
			{
				"canonicalName": "io1.in",
				"aliases": [
					"io1.in",
					"serial1.rx"
				]
			},
			{
				"canonicalName": "io1.out",
				"aliases": [
					"io1.out",
					"serial1.tx"
				]
			},
			{
				"canonicalName": "ate.sd1.cd",
				"aliases": [
					"ate.sd1.cd"
				]
			},
			{
				"canonicalName": "spi.cs3",
				"aliases": [
					"spi.cs3"
				]
			},
			{
				"canonicalName": "io5.out",
				"aliases": [
					"io5.out",
					"io5.out.iso"
				]
			},
			{
				"canonicalName": "out4.tach",
				"aliases": [
					"out4.tach"
				]
			},
			{
				"canonicalName": "rs485.tx",
				"aliases": [
					"rs485.tx"
				]
			},
			{
				"canonicalName": "io0.in",
				"aliases": [
					"io0.in",
					"serial0.rx"
				]
			},
			{
				"canonicalName": "io0.out",
				"aliases": [
					"io0.out",
					"serial0.tx"
				]
			},
			{
				"canonicalName": "io2.out",
				"aliases": [
					"io2.out",
					"i2c0.dat"
				]
			},
			{
				"canonicalName": "io2.in",
				"aliases": [
					"io2.in",
					"i2c0.clk"
				]
			},
			{
				"canonicalName": "driver0.err",
				"aliases": [
					"driver0.err"
				]
			},
			{
				"canonicalName": "io4.in",
				"aliases": [
					"io4.in"
				]
			},
			{
				"canonicalName": "driver4.err",
				"aliases": [
					"driver4.err"
				]
			},
			{
				"canonicalName": "io4.out",
				"aliases": [
					"io4.out"
				]
			},
			{
				"canonicalName": "io8.out",
				"aliases": [
					"io8.out",
					"io8.out.iso"
				]
			},
			{
				"canonicalName": "io8.in",
				"aliases": [
					"io8.in",
					"io8.in.iso"
				]
			},
			{
				"canonicalName": "io3.in",
				"aliases": [
					"io3.in"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_Duet3_MB6XD.h PinTable[]"
		]
	},
	{
		"boardId": "duet3mini",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "lcd.a0",
				"aliases": [
					"lcd.a0",
					"exp1.7",
					"spi.cs4"
				]
			},
			{
				"canonicalName": "ate.sbc.dr",
				"aliases": [
					"ate.sbc.dr"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "lcd.buzz",
				"aliases": [
					"lcd.buzz",
					"exp1.10"
				]
			},
			{
				"canonicalName": "ate.d0.diag",
				"aliases": [
					"ate.d0.diag"
				]
			},
			{
				"canonicalName": "out4",
				"aliases": [
					"out4"
				]
			},
			{
				"canonicalName": "ate.d2.diag",
				"aliases": [
					"ate.d2.diag"
				]
			},
			{
				"canonicalName": "ate.d3.diag",
				"aliases": [
					"ate.d3.diag"
				]
			},
			{
				"canonicalName": "ate.d6.dir",
				"aliases": [
					"ate.d6.dir"
				]
			},
			{
				"canonicalName": "ate.d5.dir",
				"aliases": [
					"ate.d5.dir"
				]
			},
			{
				"canonicalName": "out6",
				"aliases": [
					"out6",
					"laser",
					"vfd"
				]
			},
			{
				"canonicalName": "out5",
				"aliases": [
					"out5"
				]
			},
			{
				"canonicalName": "ate.d0.dir",
				"aliases": [
					"ate.d0.dir"
				]
			},
			{
				"canonicalName": "ate.vbus",
				"aliases": [
					"ate.vbus"
				]
			},
			{
				"canonicalName": "io3.in",
				"aliases": [
					"io3.in"
				]
			},
			{
				"canonicalName": "ate.d1.diag",
				"aliases": [
					"ate.d1.diag"
				]
			},
			{
				"canonicalName": "enc.sw",
				"aliases": [
					"enc.sw",
					"exp1.9"
				]
			},
			{
				"canonicalName": "ate.d5.diag",
				"aliases": [
					"ate.d5.diag"
				]
			},
			{
				"canonicalName": "out3",
				"aliases": [
					"out3"
				]
			},
			{
				"canonicalName": "io3.out",
				"aliases": [
					"io3.out",
					"lcd.np"
				]
			},
			{
				"canonicalName": "out2",
				"aliases": [
					"out2"
				]
			},
			{
				"canonicalName": "ate.cd",
				"aliases": [
					"ate.cd"
				]
			},
			{
				"canonicalName": "out0",
				"aliases": [
					"out0"
				]
			},
			{
				"canonicalName": "io0.in",
				"aliases": [
					"io0.in"
				]
			},
			{
				"canonicalName": "io0.out",
				"aliases": [
					"io0.out"
				]
			},
			{
				"canonicalName": "out4.tach",
				"aliases": [
					"out4.tach"
				]
			},
			{
				"canonicalName": "out3.tach",
				"aliases": [
					"out3.tach"
				]
			},
			{
				"canonicalName": "ate.d2.dir",
				"aliases": [
					"ate.d2.dir"
				]
			},
			{
				"canonicalName": "ate.d1.dir",
				"aliases": [
					"ate.d1.dir"
				]
			},
			{
				"canonicalName": "io1.in",
				"aliases": [
					"io1.in"
				]
			},
			{
				"canonicalName": "io1.out",
				"aliases": [
					"io1.out"
				]
			},
			{
				"canonicalName": "temp0",
				"aliases": [
					"temp0"
				]
			},
			{
				"canonicalName": "temp1",
				"aliases": [
					"temp1"
				]
			},
			{
				"canonicalName": "temp2",
				"aliases": [
					"temp2"
				]
			},
			{
				"canonicalName": "ate.vin",
				"aliases": [
					"ate.vin"
				]
			},
			{
				"canonicalName": "io5.in",
				"aliases": [
					"io5.in"
				]
			},
			{
				"canonicalName": "io4.in",
				"aliases": [
					"io4.in"
				]
			},
			{
				"canonicalName": "spi.cs3",
				"aliases": [
					"spi.cs3"
				]
			},
			{
				"canonicalName": "spi.cs2",
				"aliases": [
					"spi.cs2"
				]
			},
			{
				"canonicalName": "out1",
				"aliases": [
					"out1"
				]
			},
			{
				"canonicalName": "enc.a",
				"aliases": [
					"enc.a",
					"exp2.8"
				]
			},
			{
				"canonicalName": "ate.d4.step",
				"aliases": [
					"ate.d4.step"
				]
			},
			{
				"canonicalName": "ate.d6.step",
				"aliases": [
					"ate.d6.step"
				]
			},
			{
				"canonicalName": "ate.d3.step",
				"aliases": [
					"ate.d3.step"
				]
			},
			{
				"canonicalName": "ate.d6.diag",
				"aliases": [
					"ate.d6.diag"
				]
			},
			{
				"canonicalName": "ate.d2.step",
				"aliases": [
					"ate.d2.step"
				]
			},
			{
				"canonicalName": "ate.d1.step",
				"aliases": [
					"ate.d1.step"
				]
			},
			{
				"canonicalName": "ate.d0.step",
				"aliases": [
					"ate.d0.step"
				]
			},
			{
				"canonicalName": "ate.d6.diag",
				"aliases": [
					"ate.d6.diag"
				]
			},
			{
				"canonicalName": "ate.d5.step",
				"aliases": [
					"ate.d5.step"
				]
			},
			{
				"canonicalName": "io6.in",
				"aliases": [
					"io6.in"
				]
			},
			{
				"canonicalName": "enc.b",
				"aliases": [
					"enc.b"
				]
			},
			{
				"canonicalName": "io2.in",
				"aliases": [
					"io2.in",
					"i2c0.clk"
				]
			},
			{
				"canonicalName": "io2.out",
				"aliases": [
					"io2.out",
					"i2c0.dat"
				]
			},
			{
				"canonicalName": "io4.out",
				"aliases": [
					"io4.out",
					"pson"
				]
			},
			{
				"canonicalName": "spi.cs1",
				"aliases": [
					"spi.cs1"
				]
			},
			{
				"canonicalName": "ate.spi.cd",
				"aliases": [
					"ate.spi.cd"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_Duet3Mini.h PinTable[]"
		]
	},
	{
		"boardId": "duetng",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "fan2",
				"aliases": [
					"fan2"
				]
			},
			{
				"canonicalName": "ystop",
				"aliases": [
					"ystop"
				]
			},
			{
				"canonicalName": "connsd.encsw",
				"aliases": [
					"connsd.encsw",
					"connsd.7"
				]
			},
			{
				"canonicalName": "connlcd.enca",
				"aliases": [
					"connlcd.enca",
					"connlcd.4"
				]
			},
			{
				"canonicalName": "urxd0",
				"aliases": [
					"urxd0"
				]
			},
			{
				"canonicalName": "utxd0",
				"aliases": [
					"utxd0"
				]
			},
			{
				"canonicalName": "exp.heater7",
				"aliases": [
					"exp.heater7",
					"exp.31",
					"duex.e6heat",
					"duex.pwm5"
				]
			},
			{
				"canonicalName": "e1heat",
				"aliases": [
					"e1heat"
				]
			},
			{
				"canonicalName": "exp.e6stop",
				"aliases": [
					"exp.e6stop",
					"exp.24"
				]
			},
			{
				"canonicalName": "e6temp",
				"aliases": [
					"e6temp",
					"duex.e6temp",
					"exp.thermistor7",
					"exp.39"
				]
			},
			{
				"canonicalName": "bedheat",
				"aliases": [
					"bedheat"
				]
			},
			{
				"canonicalName": "e0heat",
				"aliases": [
					"e0heat"
				]
			},
			{
				"canonicalName": "spi.cs5",
				"aliases": [
					"spi.cs5",
					"duex.cs5",
					"exp.50"
				]
			},
			{
				"canonicalName": "connlcd.en",
				"aliases": [
					"connlcd.en",
					"connlcd.8"
				]
			},
			{
				"canonicalName": "spi.cs1",
				"aliases": [
					"spi.cs1"
				]
			},
			{
				"canonicalName": "exp.pb6",
				"aliases": [
					"exp.pb6",
					"exp.29",
					"duex.pb6"
				]
			},
			{
				"canonicalName": "zprobe.in",
				"aliases": [
					"zprobe.in"
				]
			},
			{
				"canonicalName": "zprobe.mod",
				"aliases": [
					"zprobe.mod"
				]
			},
			{
				"canonicalName": "exp.heater3",
				"aliases": [
					"exp.heater3",
					"exp.8",
					"duex.e2heat",
					"duex.pwm1"
				]
			},
			{
				"canonicalName": "exp.heater4",
				"aliases": [
					"exp.heater4",
					"exp.13",
					"duex.e3heat",
					"duex.pwm2"
				]
			},
			{
				"canonicalName": "connlcd.encb",
				"aliases": [
					"connlcd.encb",
					"connlcd.3"
				]
			},
			{
				"canonicalName": "exp.heater5",
				"aliases": [
					"exp.heater5",
					"exp.18",
					"duex.e4heat",
					"duex.pwm3"
				]
			},
			{
				"canonicalName": "exp.heater6",
				"aliases": [
					"exp.heater6",
					"exp.23",
					"duex.e5heat",
					"duex.pwm4"
				]
			},
			{
				"canonicalName": "e1temp",
				"aliases": [
					"e1temp"
				]
			},
			{
				"canonicalName": "bedtemp",
				"aliases": [
					"bedtemp"
				]
			},
			{
				"canonicalName": "xstop",
				"aliases": [
					"xstop"
				]
			},
			{
				"canonicalName": "e0temp",
				"aliases": [
					"e0temp"
				]
			},
			{
				"canonicalName": "e1stop",
				"aliases": [
					"e1stop"
				]
			},
			{
				"canonicalName": "spi.cs2",
				"aliases": [
					"spi.cs2"
				]
			},
			{
				"canonicalName": "spi.cs3",
				"aliases": [
					"spi.cs3"
				]
			},
			{
				"canonicalName": "spi.cs4",
				"aliases": [
					"spi.cs4"
				]
			},
			{
				"canonicalName": "fan0",
				"aliases": [
					"fan0"
				]
			},
			{
				"canonicalName": "fan1",
				"aliases": [
					"fan1"
				]
			},
			{
				"canonicalName": "e5temp",
				"aliases": [
					"e5temp",
					"duex.e5temp",
					"exp.thermistor6",
					"exp.38"
				]
			},
			{
				"canonicalName": "connlcd.rs",
				"aliases": [
					"connlcd.rs",
					"connlcd.6"
				]
			},
			{
				"canonicalName": "e2temp",
				"aliases": [
					"e2temp",
					"duex.e2temp",
					"exp.thermistor3",
					"exp.35"
				]
			},
			{
				"canonicalName": "e3temp",
				"aliases": [
					"e3temp",
					"duex.e3temp",
					"exp.thermistor4",
					"exp.36"
				]
			},
			{
				"canonicalName": "e4temp",
				"aliases": [
					"e4temp",
					"duex.e4temp",
					"exp.thermistor5",
					"exp.37"
				]
			},
			{
				"canonicalName": "e0stop",
				"aliases": [
					"e0stop"
				]
			},
			{
				"canonicalName": "pson",
				"aliases": [
					"pson"
				]
			},
			{
				"canonicalName": "connlcd.np",
				"aliases": [
					"connlcd.np",
					"connlcd.db7",
					"connlcd.5"
				]
			},
			{
				"canonicalName": "connlcd.db6",
				"aliases": [
					"connlcd.db6",
					"connlcd.7"
				]
			},
			{
				"canonicalName": "connlcd.db5",
				"aliases": [
					"connlcd.db5",
					"connlcd.9"
				]
			},
			{
				"canonicalName": "connlcd.db4",
				"aliases": [
					"connlcd.db4",
					"connlcd.10"
				]
			},
			{
				"canonicalName": "zstop",
				"aliases": [
					"zstop"
				]
			},
			{
				"canonicalName": "exp.e2stop",
				"aliases": [
					"exp.e2stop",
					"exp.4"
				]
			},
			{
				"canonicalName": "exp.e3stop",
				"aliases": [
					"exp.e3stop",
					"exp.9",
					"spi.cs6",
					"duex.cs6"
				]
			},
			{
				"canonicalName": "exp.e4stop",
				"aliases": [
					"exp.e4stop",
					"exp.14",
					"spi.cs7",
					"duex.cs7"
				]
			},
			{
				"canonicalName": "exp.e5stop",
				"aliases": [
					"exp.e5stop",
					"exp.19",
					"spi.cs8",
					"duex.cs8"
				]
			},
			{
				"canonicalName": "duex.e2stop",
				"aliases": [
					"duex.e2stop"
				]
			},
			{
				"canonicalName": "duex.e5stop",
				"aliases": [
					"duex.e5stop"
				]
			},
			{
				"canonicalName": "duex.e4stop",
				"aliases": [
					"duex.e4stop"
				]
			},
			{
				"canonicalName": "duex.e3stop",
				"aliases": [
					"duex.e3stop"
				]
			},
			{
				"canonicalName": "duex.fan7",
				"aliases": [
					"duex.fan7"
				]
			},
			{
				"canonicalName": "duex.fan6",
				"aliases": [
					"duex.fan6"
				]
			},
			{
				"canonicalName": "duex.fan5",
				"aliases": [
					"duex.fan5"
				]
			},
			{
				"canonicalName": "duex.fan4",
				"aliases": [
					"duex.fan4"
				]
			},
			{
				"canonicalName": "duex.gp4",
				"aliases": [
					"duex.gp4"
				]
			},
			{
				"canonicalName": "duex.gp3",
				"aliases": [
					"duex.gp3"
				]
			},
			{
				"canonicalName": "duex.gp2",
				"aliases": [
					"duex.gp2"
				]
			},
			{
				"canonicalName": "duex.gp1",
				"aliases": [
					"duex.gp1"
				]
			},
			{
				"canonicalName": "duex.fan3",
				"aliases": [
					"duex.fan3"
				]
			},
			{
				"canonicalName": "duex.e6stop",
				"aliases": [
					"duex.e6stop"
				]
			},
			{
				"canonicalName": "duex.fan8",
				"aliases": [
					"duex.fan8"
				]
			},
			{
				"canonicalName": "sx1509b.0",
				"aliases": [
					"sx1509b.0"
				]
			},
			{
				"canonicalName": "sx1509b.1",
				"aliases": [
					"sx1509b.1"
				]
			},
			{
				"canonicalName": "sx1509b.2",
				"aliases": [
					"sx1509b.2"
				]
			},
			{
				"canonicalName": "sx1509b.3",
				"aliases": [
					"sx1509b.3"
				]
			},
			{
				"canonicalName": "sx1509b.4",
				"aliases": [
					"sx1509b.4"
				]
			},
			{
				"canonicalName": "sx1509b.5",
				"aliases": [
					"sx1509b.5"
				]
			},
			{
				"canonicalName": "sx1509b.6",
				"aliases": [
					"sx1509b.6"
				]
			},
			{
				"canonicalName": "sx1509b.7",
				"aliases": [
					"sx1509b.7"
				]
			},
			{
				"canonicalName": "sx1509b.8",
				"aliases": [
					"sx1509b.8"
				]
			},
			{
				"canonicalName": "sx1509b.9",
				"aliases": [
					"sx1509b.9"
				]
			},
			{
				"canonicalName": "sx1509b.10",
				"aliases": [
					"sx1509b.10"
				]
			},
			{
				"canonicalName": "sx1509b.11",
				"aliases": [
					"sx1509b.11"
				]
			},
			{
				"canonicalName": "sx1509b.12",
				"aliases": [
					"sx1509b.12"
				]
			},
			{
				"canonicalName": "sx1509b.13",
				"aliases": [
					"sx1509b.13"
				]
			},
			{
				"canonicalName": "sx1509b.14",
				"aliases": [
					"sx1509b.14"
				]
			},
			{
				"canonicalName": "sx1509b.15",
				"aliases": [
					"sx1509b.15"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_DuetNG.h PinTable[]"
		]
	},
	{
		"boardId": "pccb",
		"family": "duet-compiled",
		"pins": [
			{
				"canonicalName": "fan1",
				"aliases": [
					"fan1"
				]
			},
			{
				"canonicalName": "fan0",
				"aliases": [
					"fan0"
				]
			},
			{
				"canonicalName": "exp.pa18",
				"aliases": [
					"exp.pa18",
					"exp.35"
				]
			},
			{
				"canonicalName": "temp0",
				"aliases": [
					"temp0"
				]
			},
			{
				"canonicalName": "exp.pa21",
				"aliases": [
					"exp.pa21",
					"exp.36"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "stop0",
				"aliases": [
					"stop0"
				]
			},
			{
				"canonicalName": "stop1",
				"aliases": [
					"stop1"
				]
			},
			{
				"canonicalName": "fan5a.tach",
				"aliases": [
					"fan5a.tach"
				]
			},
			{
				"canonicalName": "fan3",
				"aliases": [
					"fan3"
				]
			},
			{
				"canonicalName": "fan4",
				"aliases": [
					"fan4"
				]
			},
			{
				"canonicalName": "led",
				"aliases": [
					"led"
				]
			},
			{
				"canonicalName": "fan5",
				"aliases": [
					"fan5"
				]
			},
			{
				"canonicalName": "fan2",
				"aliases": [
					"fan2"
				]
			},
			{
				"canonicalName": "stop2",
				"aliases": [
					"stop2"
				]
			},
			{
				"canonicalName": "temp1",
				"aliases": [
					"temp1"
				]
			},
			{
				"canonicalName": "fan1",
				"aliases": [
					"fan1"
				]
			},
			{
				"canonicalName": "leddim",
				"aliases": [
					"leddim"
				]
			},
			{
				"canonicalName": "exp.pc26",
				"aliases": [
					"exp.pc26",
					"exp.13",
					"duex.heater4"
				]
			},
			{
				"canonicalName": "exp.pc27",
				"aliases": [
					"exp.pc27",
					"exp.9",
					"spi.cs6",
					"stop3"
				]
			},
			{
				"canonicalName": "exp.pc29",
				"aliases": [
					"exp.pc29",
					"exp.8",
					"duex.heater3"
				]
			},
			{
				"canonicalName": "fan5b.tach",
				"aliases": [
					"fan5b.tach"
				]
			}
		],
		"sources": [
			"RRF 3.7.0-rc.1 Config/Pins_Pccb.h PinTable[]"
		]
	}
]
);
